// Code generated by ent, DO NOT EDIT.

package song

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the song type in the database.
	Label = "song"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldArtist holds the string denoting the artist field in the database.
	FieldArtist = "artist"
	// FieldAlbum holds the string denoting the album field in the database.
	FieldAlbum = "album"
	// FieldGenre holds the string denoting the genre field in the database.
	FieldGenre = "genre"
	// FieldTrackNumber holds the string denoting the track_number field in the database.
	FieldTrackNumber = "track_number"
	// FieldDiscNumber holds the string denoting the disc_number field in the database.
	FieldDiscNumber = "disc_number"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldFileSize holds the string denoting the file_size field in the database.
	FieldFileSize = "file_size"
	// FieldFileHash holds the string denoting the file_hash field in the database.
	FieldFileHash = "file_hash"
	// FieldMimeType holds the string denoting the mime_type field in the database.
	FieldMimeType = "mime_type"
	// FieldBitrate holds the string denoting the bitrate field in the database.
	FieldBitrate = "bitrate"
	// FieldSampleRate holds the string denoting the sample_rate field in the database.
	FieldSampleRate = "sample_rate"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldFileStatus holds the string denoting the file_status field in the database.
	FieldFileStatus = "file_status"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the song in the database.
	Table = "songs"
)

// Columns holds all SQL columns for song fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldArtist,
	FieldAlbum,
	FieldGenre,
	FieldTrackNumber,
	FieldDiscNumber,
	FieldDurationMs,
	FieldYear,
	FieldFileName,
	FieldFileSize,
	FieldFileHash,
	FieldMimeType,
	FieldBitrate,
	FieldSampleRate,
	FieldSource,
	FieldFileStatus,
	FieldOwnerID,
	FieldIsDeleted,
	FieldVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultArtist holds the default value on creation for the "artist" field.
	DefaultArtist string
	// ArtistValidator is a validator for the "artist" field. It is called by the builders before save.
	ArtistValidator func(string) error
	// DefaultAlbum holds the default value on creation for the "album" field.
	DefaultAlbum string
	// AlbumValidator is a validator for the "album" field. It is called by the builders before save.
	AlbumValidator func(string) error
	// DefaultGenre holds the default value on creation for the "genre" field.
	DefaultGenre string
	// GenreValidator is a validator for the "genre" field. It is called by the builders before save.
	GenreValidator func(string) error
	// DefaultTrackNumber holds the default value on creation for the "track_number" field.
	DefaultTrackNumber int32
	// DefaultDiscNumber holds the default value on creation for the "disc_number" field.
	DefaultDiscNumber int32
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int32
	// DefaultYear holds the default value on creation for the "year" field.
	DefaultYear int32
	// DefaultFileName holds the default value on creation for the "file_name" field.
	DefaultFileName string
	// FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	FileNameValidator func(string) error
	// DefaultFileSize holds the default value on creation for the "file_size" field.
	DefaultFileSize int64
	// DefaultFileHash holds the default value on creation for the "file_hash" field.
	DefaultFileHash string
	// FileHashValidator is a validator for the "file_hash" field. It is called by the builders before save.
	FileHashValidator func(string) error
	// DefaultMimeType holds the default value on creation for the "mime_type" field.
	DefaultMimeType string
	// MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	MimeTypeValidator func(string) error
	// DefaultBitrate holds the default value on creation for the "bitrate" field.
	DefaultBitrate int32
	// DefaultSampleRate holds the default value on creation for the "sample_rate" field.
	DefaultSampleRate int32
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultFileStatus holds the default value on creation for the "file_status" field.
	DefaultFileStatus string
	// DefaultOwnerID holds the default value on creation for the "owner_id" field.
	DefaultOwnerID string
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted bool
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
)

// OrderOption defines the ordering options for the Song queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByArtist orders the results by the artist field.
func ByArtist(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtist, opts...).ToFunc()
}

// ByAlbum orders the results by the album field.
func ByAlbum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlbum, opts...).ToFunc()
}

// ByGenre orders the results by the genre field.
func ByGenre(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenre, opts...).ToFunc()
}

// ByTrackNumber orders the results by the track_number field.
func ByTrackNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackNumber, opts...).ToFunc()
}

// ByDiscNumber orders the results by the disc_number field.
func ByDiscNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscNumber, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByFileSize orders the results by the file_size field.
func ByFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSize, opts...).ToFunc()
}

// ByFileHash orders the results by the file_hash field.
func ByFileHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileHash, opts...).ToFunc()
}

// ByMimeType orders the results by the mime_type field.
func ByMimeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMimeType, opts...).ToFunc()
}

// ByBitrate orders the results by the bitrate field.
func ByBitrate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBitrate, opts...).ToFunc()
}

// BySampleRate orders the results by the sample_rate field.
func BySampleRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSampleRate, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByFileStatus orders the results by the file_status field.
func ByFileStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileStatus, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByIsDeleted orders the results by the is_deleted field.
func ByIsDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDeleted, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
