// Code generated by ent, DO NOT EDIT.

package song

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldTitle, v))
}

// Artist applies equality check predicate on the "artist" field. It's identical to ArtistEQ.
func Artist(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldArtist, v))
}

// Album applies equality check predicate on the "album" field. It's identical to AlbumEQ.
func Album(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldAlbum, v))
}

// Genre applies equality check predicate on the "genre" field. It's identical to GenreEQ.
func Genre(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldGenre, v))
}

// TrackNumber applies equality check predicate on the "track_number" field. It's identical to TrackNumberEQ.
func TrackNumber(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldTrackNumber, v))
}

// DiscNumber applies equality check predicate on the "disc_number" field. It's identical to DiscNumberEQ.
func DiscNumber(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldDiscNumber, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldDurationMs, v))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldYear, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldFileName, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldFileSize, v))
}

// FileHash applies equality check predicate on the "file_hash" field. It's identical to FileHashEQ.
func FileHash(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldFileHash, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldMimeType, v))
}

// Bitrate applies equality check predicate on the "bitrate" field. It's identical to BitrateEQ.
func Bitrate(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldBitrate, v))
}

// SampleRate applies equality check predicate on the "sample_rate" field. It's identical to SampleRateEQ.
func SampleRate(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldSampleRate, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldSource, v))
}

// FileStatus applies equality check predicate on the "file_status" field. It's identical to FileStatusEQ.
func FileStatus(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldFileStatus, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldOwnerID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldVersion, v))
}

// IsDeleted applies equality check predicate on the "is_deleted" field. It's identical to IsDeletedEQ.
func IsDeleted(v bool) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldIsDeleted, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldTitle, v))
}

// ArtistEQ applies the EQ predicate on the "artist" field.
func ArtistEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldArtist, v))
}

// ArtistNEQ applies the NEQ predicate on the "artist" field.
func ArtistNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldArtist, v))
}

// ArtistIn applies the In predicate on the "artist" field.
func ArtistIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldArtist, vs...))
}

// ArtistNotIn applies the NotIn predicate on the "artist" field.
func ArtistNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldArtist, vs...))
}

// ArtistGT applies the GT predicate on the "artist" field.
func ArtistGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldArtist, v))
}

// ArtistGTE applies the GTE predicate on the "artist" field.
func ArtistGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldArtist, v))
}

// ArtistLT applies the LT predicate on the "artist" field.
func ArtistLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldArtist, v))
}

// ArtistLTE applies the LTE predicate on the "artist" field.
func ArtistLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldArtist, v))
}

// ArtistContains applies the Contains predicate on the "artist" field.
func ArtistContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldArtist, v))
}

// ArtistHasPrefix applies the HasPrefix predicate on the "artist" field.
func ArtistHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldArtist, v))
}

// ArtistHasSuffix applies the HasSuffix predicate on the "artist" field.
func ArtistHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldArtist, v))
}

// ArtistEqualFold applies the EqualFold predicate on the "artist" field.
func ArtistEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldArtist, v))
}

// ArtistContainsFold applies the ContainsFold predicate on the "artist" field.
func ArtistContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldArtist, v))
}

// AlbumEQ applies the EQ predicate on the "album" field.
func AlbumEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldAlbum, v))
}

// AlbumNEQ applies the NEQ predicate on the "album" field.
func AlbumNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldAlbum, v))
}

// AlbumIn applies the In predicate on the "album" field.
func AlbumIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldAlbum, vs...))
}

// AlbumNotIn applies the NotIn predicate on the "album" field.
func AlbumNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldAlbum, vs...))
}

// AlbumGT applies the GT predicate on the "album" field.
func AlbumGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldAlbum, v))
}

// AlbumGTE applies the GTE predicate on the "album" field.
func AlbumGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldAlbum, v))
}

// AlbumLT applies the LT predicate on the "album" field.
func AlbumLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldAlbum, v))
}

// AlbumLTE applies the LTE predicate on the "album" field.
func AlbumLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldAlbum, v))
}

// AlbumContains applies the Contains predicate on the "album" field.
func AlbumContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldAlbum, v))
}

// AlbumHasPrefix applies the HasPrefix predicate on the "album" field.
func AlbumHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldAlbum, v))
}

// AlbumHasSuffix applies the HasSuffix predicate on the "album" field.
func AlbumHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldAlbum, v))
}

// AlbumEqualFold applies the EqualFold predicate on the "album" field.
func AlbumEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldAlbum, v))
}

// AlbumContainsFold applies the ContainsFold predicate on the "album" field.
func AlbumContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldAlbum, v))
}

// GenreEQ applies the EQ predicate on the "genre" field.
func GenreEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldGenre, v))
}

// GenreNEQ applies the NEQ predicate on the "genre" field.
func GenreNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldGenre, v))
}

// GenreIn applies the In predicate on the "genre" field.
func GenreIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldGenre, vs...))
}

// GenreNotIn applies the NotIn predicate on the "genre" field.
func GenreNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldGenre, vs...))
}

// GenreGT applies the GT predicate on the "genre" field.
func GenreGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldGenre, v))
}

// GenreGTE applies the GTE predicate on the "genre" field.
func GenreGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldGenre, v))
}

// GenreLT applies the LT predicate on the "genre" field.
func GenreLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldGenre, v))
}

// GenreLTE applies the LTE predicate on the "genre" field.
func GenreLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldGenre, v))
}

// GenreContains applies the Contains predicate on the "genre" field.
func GenreContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldGenre, v))
}

// GenreHasPrefix applies the HasPrefix predicate on the "genre" field.
func GenreHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldGenre, v))
}

// GenreHasSuffix applies the HasSuffix predicate on the "genre" field.
func GenreHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldGenre, v))
}

// GenreEqualFold applies the EqualFold predicate on the "genre" field.
func GenreEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldGenre, v))
}

// GenreContainsFold applies the ContainsFold predicate on the "genre" field.
func GenreContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldGenre, v))
}

// TrackNumberEQ applies the EQ predicate on the "track_number" field.
func TrackNumberEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldTrackNumber, v))
}

// TrackNumberNEQ applies the NEQ predicate on the "track_number" field.
func TrackNumberNEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldTrackNumber, v))
}

// TrackNumberIn applies the In predicate on the "track_number" field.
func TrackNumberIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldTrackNumber, vs...))
}

// TrackNumberNotIn applies the NotIn predicate on the "track_number" field.
func TrackNumberNotIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldTrackNumber, vs...))
}

// TrackNumberGT applies the GT predicate on the "track_number" field.
func TrackNumberGT(v int32) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldTrackNumber, v))
}

// TrackNumberGTE applies the GTE predicate on the "track_number" field.
func TrackNumberGTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldTrackNumber, v))
}

// TrackNumberLT applies the LT predicate on the "track_number" field.
func TrackNumberLT(v int32) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldTrackNumber, v))
}

// TrackNumberLTE applies the LTE predicate on the "track_number" field.
func TrackNumberLTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldTrackNumber, v))
}

// DiscNumberEQ applies the EQ predicate on the "disc_number" field.
func DiscNumberEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldDiscNumber, v))
}

// DiscNumberNEQ applies the NEQ predicate on the "disc_number" field.
func DiscNumberNEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldDiscNumber, v))
}

// DiscNumberIn applies the In predicate on the "disc_number" field.
func DiscNumberIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldDiscNumber, vs...))
}

// DiscNumberNotIn applies the NotIn predicate on the "disc_number" field.
func DiscNumberNotIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldDiscNumber, vs...))
}

// DiscNumberGT applies the GT predicate on the "disc_number" field.
func DiscNumberGT(v int32) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldDiscNumber, v))
}

// DiscNumberGTE applies the GTE predicate on the "disc_number" field.
func DiscNumberGTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldDiscNumber, v))
}

// DiscNumberLT applies the LT predicate on the "disc_number" field.
func DiscNumberLT(v int32) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldDiscNumber, v))
}

// DiscNumberLTE applies the LTE predicate on the "disc_number" field.
func DiscNumberLTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldDiscNumber, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int32) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int32) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldDurationMs, v))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v int32) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v int32) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldYear, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldFileName, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldFileSize, v))
}

// FileHashEQ applies the EQ predicate on the "file_hash" field.
func FileHashEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldFileHash, v))
}

// FileHashNEQ applies the NEQ predicate on the "file_hash" field.
func FileHashNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldFileHash, v))
}

// FileHashIn applies the In predicate on the "file_hash" field.
func FileHashIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldFileHash, vs...))
}

// FileHashNotIn applies the NotIn predicate on the "file_hash" field.
func FileHashNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldFileHash, vs...))
}

// FileHashGT applies the GT predicate on the "file_hash" field.
func FileHashGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldFileHash, v))
}

// FileHashGTE applies the GTE predicate on the "file_hash" field.
func FileHashGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldFileHash, v))
}

// FileHashLT applies the LT predicate on the "file_hash" field.
func FileHashLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldFileHash, v))
}

// FileHashLTE applies the LTE predicate on the "file_hash" field.
func FileHashLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldFileHash, v))
}

// FileHashContains applies the Contains predicate on the "file_hash" field.
func FileHashContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldFileHash, v))
}

// FileHashHasPrefix applies the HasPrefix predicate on the "file_hash" field.
func FileHashHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldFileHash, v))
}

// FileHashHasSuffix applies the HasSuffix predicate on the "file_hash" field.
func FileHashHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldFileHash, v))
}

// FileHashEqualFold applies the EqualFold predicate on the "file_hash" field.
func FileHashEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldFileHash, v))
}

// FileHashContainsFold applies the ContainsFold predicate on the "file_hash" field.
func FileHashContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldFileHash, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldMimeType, v))
}

// BitrateEQ applies the EQ predicate on the "bitrate" field.
func BitrateEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldBitrate, v))
}

// BitrateNEQ applies the NEQ predicate on the "bitrate" field.
func BitrateNEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldBitrate, v))
}

// BitrateIn applies the In predicate on the "bitrate" field.
func BitrateIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldBitrate, vs...))
}

// BitrateNotIn applies the NotIn predicate on the "bitrate" field.
func BitrateNotIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldBitrate, vs...))
}

// BitrateGT applies the GT predicate on the "bitrate" field.
func BitrateGT(v int32) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldBitrate, v))
}

// BitrateGTE applies the GTE predicate on the "bitrate" field.
func BitrateGTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldBitrate, v))
}

// BitrateLT applies the LT predicate on the "bitrate" field.
func BitrateLT(v int32) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldBitrate, v))
}

// BitrateLTE applies the LTE predicate on the "bitrate" field.
func BitrateLTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldBitrate, v))
}

// SampleRateEQ applies the EQ predicate on the "sample_rate" field.
func SampleRateEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldSampleRate, v))
}

// SampleRateNEQ applies the NEQ predicate on the "sample_rate" field.
func SampleRateNEQ(v int32) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldSampleRate, v))
}

// SampleRateIn applies the In predicate on the "sample_rate" field.
func SampleRateIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldSampleRate, vs...))
}

// SampleRateNotIn applies the NotIn predicate on the "sample_rate" field.
func SampleRateNotIn(vs ...int32) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldSampleRate, vs...))
}

// SampleRateGT applies the GT predicate on the "sample_rate" field.
func SampleRateGT(v int32) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldSampleRate, v))
}

// SampleRateGTE applies the GTE predicate on the "sample_rate" field.
func SampleRateGTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldSampleRate, v))
}

// SampleRateLT applies the LT predicate on the "sample_rate" field.
func SampleRateLT(v int32) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldSampleRate, v))
}

// SampleRateLTE applies the LTE predicate on the "sample_rate" field.
func SampleRateLTE(v int32) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldSampleRate, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldSource, v))
}

// FileStatusEQ applies the EQ predicate on the "file_status" field.
func FileStatusEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldFileStatus, v))
}

// FileStatusNEQ applies the NEQ predicate on the "file_status" field.
func FileStatusNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldFileStatus, v))
}

// FileStatusIn applies the In predicate on the "file_status" field.
func FileStatusIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldFileStatus, vs...))
}

// FileStatusNotIn applies the NotIn predicate on the "file_status" field.
func FileStatusNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldFileStatus, vs...))
}

// FileStatusGT applies the GT predicate on the "file_status" field.
func FileStatusGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldFileStatus, v))
}

// FileStatusGTE applies the GTE predicate on the "file_status" field.
func FileStatusGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldFileStatus, v))
}

// FileStatusLT applies the LT predicate on the "file_status" field.
func FileStatusLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldFileStatus, v))
}

// FileStatusLTE applies the LTE predicate on the "file_status" field.
func FileStatusLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldFileStatus, v))
}

// FileStatusContains applies the Contains predicate on the "file_status" field.
func FileStatusContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldFileStatus, v))
}

// FileStatusHasPrefix applies the HasPrefix predicate on the "file_status" field.
func FileStatusHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldFileStatus, v))
}

// FileStatusHasSuffix applies the HasSuffix predicate on the "file_status" field.
func FileStatusHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldFileStatus, v))
}

// FileStatusEqualFold applies the EqualFold predicate on the "file_status" field.
func FileStatusEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldFileStatus, v))
}

// FileStatusContainsFold applies the ContainsFold predicate on the "file_status" field.
func FileStatusContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldFileStatus, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldOwnerID, v))
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldOwnerID, v))
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldOwnerID, v))
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldOwnerID, v))
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldOwnerID, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldVersion, v))
}

// IsDeletedEQ applies the EQ predicate on the "is_deleted" field.
func IsDeletedEQ(v bool) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldIsDeleted, v))
}

// IsDeletedNEQ applies the NEQ predicate on the "is_deleted" field.
func IsDeletedNEQ(v bool) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldIsDeleted, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Song) predicate.Song {
	return predicate.Song(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Song) predicate.Song {
	return predicate.Song(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Song) predicate.Song {
	return predicate.Song(sql.NotPredicates(p))
}
