// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "device_id", Type: field.TypeString, Unique: true},
		{Name: "device_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "platform", Type: field.TypeString, Default: ""},
		{Name: "os_version", Type: field.TypeString, Default: ""},
		{Name: "client_version", Type: field.TypeString, Default: ""},
		{Name: "user_id", Type: field.TypeString},
		{Name: "last_sync_at", Type: field.TypeTime, Nullable: true},
		{Name: "sync_state", Type: field.TypeString, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "device_user_id",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[6]},
			},
		},
	}
	// LyricsColumns holds the columns for the "lyrics" table.
	LyricsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "song_id", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "type", Type: field.TypeString, Default: "original"},
		{Name: "language", Type: field.TypeString, Default: ""},
		{Name: "offset_ms", Type: field.TypeInt32, Default: 0},
		{Name: "source", Type: field.TypeString, Default: "manual"},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "version", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// LyricsTable holds the schema information for the "lyrics" table.
	LyricsTable = &schema.Table{
		Name:       "lyrics",
		Columns:    LyricsColumns,
		PrimaryKey: []*schema.Column{LyricsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "lyric_song_id",
				Unique:  false,
				Columns: []*schema.Column{LyricsColumns[1]},
			},
		},
	}
	// PlaylistsColumns holds the columns for the "playlists" table.
	PlaylistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Size: 256},
		{Name: "description", Type: field.TypeString, Size: 1024, Default: ""},
		{Name: "cover_url", Type: field.TypeString, Default: ""},
		{Name: "type", Type: field.TypeString, Default: "user"},
		{Name: "owner_id", Type: field.TypeString},
		{Name: "is_public", Type: field.TypeBool, Default: false},
		{Name: "song_count", Type: field.TypeInt32, Default: 0},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "version", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PlaylistsTable holds the schema information for the "playlists" table.
	PlaylistsTable = &schema.Table{
		Name:       "playlists",
		Columns:    PlaylistsColumns,
		PrimaryKey: []*schema.Column{PlaylistsColumns[0]},
	}
	// PlaylistSongsColumns holds the columns for the "playlist_songs" table.
	PlaylistSongsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "playlist_id", Type: field.TypeString},
		{Name: "song_id", Type: field.TypeString},
		{Name: "position", Type: field.TypeInt32, Default: 0},
		{Name: "added_by", Type: field.TypeString, Default: ""},
		{Name: "version", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PlaylistSongsTable holds the schema information for the "playlist_songs" table.
	PlaylistSongsTable = &schema.Table{
		Name:       "playlist_songs",
		Columns:    PlaylistSongsColumns,
		PrimaryKey: []*schema.Column{PlaylistSongsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "playlistsong_playlist_id_song_id",
				Unique:  true,
				Columns: []*schema.Column{PlaylistSongsColumns[1], PlaylistSongsColumns[2]},
			},
			{
				Name:    "playlistsong_playlist_id_position",
				Unique:  false,
				Columns: []*schema.Column{PlaylistSongsColumns[1], PlaylistSongsColumns[3]},
			},
		},
	}
	// SongsColumns holds the columns for the "songs" table.
	SongsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString, Size: 512},
		{Name: "artist", Type: field.TypeString, Size: 256, Default: ""},
		{Name: "album", Type: field.TypeString, Size: 256, Default: ""},
		{Name: "genre", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "track_number", Type: field.TypeInt32, Default: 0},
		{Name: "disc_number", Type: field.TypeInt32, Default: 1},
		{Name: "duration_ms", Type: field.TypeInt32, Default: 0},
		{Name: "year", Type: field.TypeInt32, Default: 0},
		{Name: "file_name", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "file_size", Type: field.TypeInt64, Default: 0},
		{Name: "file_hash", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "mime_type", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "bitrate", Type: field.TypeInt32, Default: 0},
		{Name: "sample_rate", Type: field.TypeInt32, Default: 0},
		{Name: "source", Type: field.TypeString, Default: "local"},
		{Name: "file_status", Type: field.TypeString, Default: "local_only"},
		{Name: "owner_id", Type: field.TypeString, Default: ""},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "version", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SongsTable holds the schema information for the "songs" table.
	SongsTable = &schema.Table{
		Name:       "songs",
		Columns:    SongsColumns,
		PrimaryKey: []*schema.Column{SongsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "song_file_hash",
				Unique:  false,
				Columns: []*schema.Column{SongsColumns[11]},
			},
			{
				Name:    "song_owner_id",
				Unique:  false,
				Columns: []*schema.Column{SongsColumns[17]},
			},
			{
				Name:    "song_title_artist",
				Unique:  false,
				Columns: []*schema.Column{SongsColumns[1], SongsColumns[2]},
			},
		},
	}
	// SyncLogsColumns holds the columns for the "sync_logs" table.
	SyncLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "device_id", Type: field.TypeString},
		{Name: "entity_type", Type: field.TypeString},
		{Name: "entity_id", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "version", Type: field.TypeInt64},
		{Name: "data", Type: field.TypeBytes, Nullable: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "acked", Type: field.TypeBool, Default: false},
	}
	// SyncLogsTable holds the schema information for the "sync_logs" table.
	SyncLogsTable = &schema.Table{
		Name:       "sync_logs",
		Columns:    SyncLogsColumns,
		PrimaryKey: []*schema.Column{SyncLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "synclog_device_id_version",
				Unique:  false,
				Columns: []*schema.Column{SyncLogsColumns[1], SyncLogsColumns[5]},
			},
			{
				Name:    "synclog_acked",
				Unique:  false,
				Columns: []*schema.Column{SyncLogsColumns[8]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "display_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "version", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DevicesTable,
		LyricsTable,
		PlaylistsTable,
		PlaylistSongsTable,
		SongsTable,
		SyncLogsTable,
		UsersTable,
	}
)

func init() {
}
