// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/device"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/lyric"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/playlist"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/playlistsong"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/song"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/synclog"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Device is the client for interacting with the Device builders.
	Device *DeviceClient
	// Lyric is the client for interacting with the Lyric builders.
	Lyric *LyricClient
	// Playlist is the client for interacting with the Playlist builders.
	Playlist *PlaylistClient
	// PlaylistSong is the client for interacting with the PlaylistSong builders.
	PlaylistSong *PlaylistSongClient
	// Song is the client for interacting with the Song builders.
	Song *SongClient
	// SyncLog is the client for interacting with the SyncLog builders.
	SyncLog *SyncLogClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Device = NewDeviceClient(c.config)
	c.Lyric = NewLyricClient(c.config)
	c.Playlist = NewPlaylistClient(c.config)
	c.PlaylistSong = NewPlaylistSongClient(c.config)
	c.Song = NewSongClient(c.config)
	c.SyncLog = NewSyncLogClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Device:       NewDeviceClient(cfg),
		Lyric:        NewLyricClient(cfg),
		Playlist:     NewPlaylistClient(cfg),
		PlaylistSong: NewPlaylistSongClient(cfg),
		Song:         NewSongClient(cfg),
		SyncLog:      NewSyncLogClient(cfg),
		User:         NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Device:       NewDeviceClient(cfg),
		Lyric:        NewLyricClient(cfg),
		Playlist:     NewPlaylistClient(cfg),
		PlaylistSong: NewPlaylistSongClient(cfg),
		Song:         NewSongClient(cfg),
		SyncLog:      NewSyncLogClient(cfg),
		User:         NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Device.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Device, c.Lyric, c.Playlist, c.PlaylistSong, c.Song, c.SyncLog, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Device, c.Lyric, c.Playlist, c.PlaylistSong, c.Song, c.SyncLog, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DeviceMutation:
		return c.Device.mutate(ctx, m)
	case *LyricMutation:
		return c.Lyric.mutate(ctx, m)
	case *PlaylistMutation:
		return c.Playlist.mutate(ctx, m)
	case *PlaylistSongMutation:
		return c.PlaylistSong.mutate(ctx, m)
	case *SongMutation:
		return c.Song.mutate(ctx, m)
	case *SyncLogMutation:
		return c.SyncLog.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DeviceClient is a client for the Device schema.
type DeviceClient struct {
	config
}

// NewDeviceClient returns a client for the Device from the given config.
func NewDeviceClient(c config) *DeviceClient {
	return &DeviceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `device.Hooks(f(g(h())))`.
func (c *DeviceClient) Use(hooks ...Hook) {
	c.hooks.Device = append(c.hooks.Device, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `device.Intercept(f(g(h())))`.
func (c *DeviceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Device = append(c.inters.Device, interceptors...)
}

// Create returns a builder for creating a Device entity.
func (c *DeviceClient) Create() *DeviceCreate {
	mutation := newDeviceMutation(c.config, OpCreate)
	return &DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Device entities.
func (c *DeviceClient) CreateBulk(builders ...*DeviceCreate) *DeviceCreateBulk {
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceClient) MapCreateBulk(slice any, setFunc func(*DeviceCreate, int)) *DeviceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceCreateBulk{err: fmt.Errorf("calling to DeviceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Device.
func (c *DeviceClient) Update() *DeviceUpdate {
	mutation := newDeviceMutation(c.config, OpUpdate)
	return &DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceClient) UpdateOne(_m *Device) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDevice(_m))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceClient) UpdateOneID(id int) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDeviceID(id))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Device.
func (c *DeviceClient) Delete() *DeviceDelete {
	mutation := newDeviceMutation(c.config, OpDelete)
	return &DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceClient) DeleteOne(_m *Device) *DeviceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceClient) DeleteOneID(id int) *DeviceDeleteOne {
	builder := c.Delete().Where(device.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceDeleteOne{builder}
}

// Query returns a query builder for Device.
func (c *DeviceClient) Query() *DeviceQuery {
	return &DeviceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDevice},
		inters: c.Interceptors(),
	}
}

// Get returns a Device entity by its id.
func (c *DeviceClient) Get(ctx context.Context, id int) (*Device, error) {
	return c.Query().Where(device.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceClient) GetX(ctx context.Context, id int) *Device {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceClient) Hooks() []Hook {
	return c.hooks.Device
}

// Interceptors returns the client interceptors.
func (c *DeviceClient) Interceptors() []Interceptor {
	return c.inters.Device
}

func (c *DeviceClient) mutate(ctx context.Context, m *DeviceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Device mutation op: %q", m.Op())
	}
}

// LyricClient is a client for the Lyric schema.
type LyricClient struct {
	config
}

// NewLyricClient returns a client for the Lyric from the given config.
func NewLyricClient(c config) *LyricClient {
	return &LyricClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lyric.Hooks(f(g(h())))`.
func (c *LyricClient) Use(hooks ...Hook) {
	c.hooks.Lyric = append(c.hooks.Lyric, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `lyric.Intercept(f(g(h())))`.
func (c *LyricClient) Intercept(interceptors ...Interceptor) {
	c.inters.Lyric = append(c.inters.Lyric, interceptors...)
}

// Create returns a builder for creating a Lyric entity.
func (c *LyricClient) Create() *LyricCreate {
	mutation := newLyricMutation(c.config, OpCreate)
	return &LyricCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Lyric entities.
func (c *LyricClient) CreateBulk(builders ...*LyricCreate) *LyricCreateBulk {
	return &LyricCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LyricClient) MapCreateBulk(slice any, setFunc func(*LyricCreate, int)) *LyricCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LyricCreateBulk{err: fmt.Errorf("calling to LyricClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LyricCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LyricCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Lyric.
func (c *LyricClient) Update() *LyricUpdate {
	mutation := newLyricMutation(c.config, OpUpdate)
	return &LyricUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LyricClient) UpdateOne(_m *Lyric) *LyricUpdateOne {
	mutation := newLyricMutation(c.config, OpUpdateOne, withLyric(_m))
	return &LyricUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LyricClient) UpdateOneID(id string) *LyricUpdateOne {
	mutation := newLyricMutation(c.config, OpUpdateOne, withLyricID(id))
	return &LyricUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Lyric.
func (c *LyricClient) Delete() *LyricDelete {
	mutation := newLyricMutation(c.config, OpDelete)
	return &LyricDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LyricClient) DeleteOne(_m *Lyric) *LyricDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LyricClient) DeleteOneID(id string) *LyricDeleteOne {
	builder := c.Delete().Where(lyric.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LyricDeleteOne{builder}
}

// Query returns a query builder for Lyric.
func (c *LyricClient) Query() *LyricQuery {
	return &LyricQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLyric},
		inters: c.Interceptors(),
	}
}

// Get returns a Lyric entity by its id.
func (c *LyricClient) Get(ctx context.Context, id string) (*Lyric, error) {
	return c.Query().Where(lyric.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LyricClient) GetX(ctx context.Context, id string) *Lyric {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LyricClient) Hooks() []Hook {
	return c.hooks.Lyric
}

// Interceptors returns the client interceptors.
func (c *LyricClient) Interceptors() []Interceptor {
	return c.inters.Lyric
}

func (c *LyricClient) mutate(ctx context.Context, m *LyricMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LyricCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LyricUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LyricUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LyricDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Lyric mutation op: %q", m.Op())
	}
}

// PlaylistClient is a client for the Playlist schema.
type PlaylistClient struct {
	config
}

// NewPlaylistClient returns a client for the Playlist from the given config.
func NewPlaylistClient(c config) *PlaylistClient {
	return &PlaylistClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `playlist.Hooks(f(g(h())))`.
func (c *PlaylistClient) Use(hooks ...Hook) {
	c.hooks.Playlist = append(c.hooks.Playlist, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `playlist.Intercept(f(g(h())))`.
func (c *PlaylistClient) Intercept(interceptors ...Interceptor) {
	c.inters.Playlist = append(c.inters.Playlist, interceptors...)
}

// Create returns a builder for creating a Playlist entity.
func (c *PlaylistClient) Create() *PlaylistCreate {
	mutation := newPlaylistMutation(c.config, OpCreate)
	return &PlaylistCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Playlist entities.
func (c *PlaylistClient) CreateBulk(builders ...*PlaylistCreate) *PlaylistCreateBulk {
	return &PlaylistCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PlaylistClient) MapCreateBulk(slice any, setFunc func(*PlaylistCreate, int)) *PlaylistCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PlaylistCreateBulk{err: fmt.Errorf("calling to PlaylistClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PlaylistCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PlaylistCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Playlist.
func (c *PlaylistClient) Update() *PlaylistUpdate {
	mutation := newPlaylistMutation(c.config, OpUpdate)
	return &PlaylistUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PlaylistClient) UpdateOne(_m *Playlist) *PlaylistUpdateOne {
	mutation := newPlaylistMutation(c.config, OpUpdateOne, withPlaylist(_m))
	return &PlaylistUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PlaylistClient) UpdateOneID(id string) *PlaylistUpdateOne {
	mutation := newPlaylistMutation(c.config, OpUpdateOne, withPlaylistID(id))
	return &PlaylistUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Playlist.
func (c *PlaylistClient) Delete() *PlaylistDelete {
	mutation := newPlaylistMutation(c.config, OpDelete)
	return &PlaylistDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PlaylistClient) DeleteOne(_m *Playlist) *PlaylistDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PlaylistClient) DeleteOneID(id string) *PlaylistDeleteOne {
	builder := c.Delete().Where(playlist.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PlaylistDeleteOne{builder}
}

// Query returns a query builder for Playlist.
func (c *PlaylistClient) Query() *PlaylistQuery {
	return &PlaylistQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePlaylist},
		inters: c.Interceptors(),
	}
}

// Get returns a Playlist entity by its id.
func (c *PlaylistClient) Get(ctx context.Context, id string) (*Playlist, error) {
	return c.Query().Where(playlist.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PlaylistClient) GetX(ctx context.Context, id string) *Playlist {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PlaylistClient) Hooks() []Hook {
	return c.hooks.Playlist
}

// Interceptors returns the client interceptors.
func (c *PlaylistClient) Interceptors() []Interceptor {
	return c.inters.Playlist
}

func (c *PlaylistClient) mutate(ctx context.Context, m *PlaylistMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PlaylistCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PlaylistUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PlaylistUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PlaylistDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Playlist mutation op: %q", m.Op())
	}
}

// PlaylistSongClient is a client for the PlaylistSong schema.
type PlaylistSongClient struct {
	config
}

// NewPlaylistSongClient returns a client for the PlaylistSong from the given config.
func NewPlaylistSongClient(c config) *PlaylistSongClient {
	return &PlaylistSongClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `playlistsong.Hooks(f(g(h())))`.
func (c *PlaylistSongClient) Use(hooks ...Hook) {
	c.hooks.PlaylistSong = append(c.hooks.PlaylistSong, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `playlistsong.Intercept(f(g(h())))`.
func (c *PlaylistSongClient) Intercept(interceptors ...Interceptor) {
	c.inters.PlaylistSong = append(c.inters.PlaylistSong, interceptors...)
}

// Create returns a builder for creating a PlaylistSong entity.
func (c *PlaylistSongClient) Create() *PlaylistSongCreate {
	mutation := newPlaylistSongMutation(c.config, OpCreate)
	return &PlaylistSongCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PlaylistSong entities.
func (c *PlaylistSongClient) CreateBulk(builders ...*PlaylistSongCreate) *PlaylistSongCreateBulk {
	return &PlaylistSongCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PlaylistSongClient) MapCreateBulk(slice any, setFunc func(*PlaylistSongCreate, int)) *PlaylistSongCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PlaylistSongCreateBulk{err: fmt.Errorf("calling to PlaylistSongClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PlaylistSongCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PlaylistSongCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PlaylistSong.
func (c *PlaylistSongClient) Update() *PlaylistSongUpdate {
	mutation := newPlaylistSongMutation(c.config, OpUpdate)
	return &PlaylistSongUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PlaylistSongClient) UpdateOne(_m *PlaylistSong) *PlaylistSongUpdateOne {
	mutation := newPlaylistSongMutation(c.config, OpUpdateOne, withPlaylistSong(_m))
	return &PlaylistSongUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PlaylistSongClient) UpdateOneID(id string) *PlaylistSongUpdateOne {
	mutation := newPlaylistSongMutation(c.config, OpUpdateOne, withPlaylistSongID(id))
	return &PlaylistSongUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PlaylistSong.
func (c *PlaylistSongClient) Delete() *PlaylistSongDelete {
	mutation := newPlaylistSongMutation(c.config, OpDelete)
	return &PlaylistSongDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PlaylistSongClient) DeleteOne(_m *PlaylistSong) *PlaylistSongDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PlaylistSongClient) DeleteOneID(id string) *PlaylistSongDeleteOne {
	builder := c.Delete().Where(playlistsong.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PlaylistSongDeleteOne{builder}
}

// Query returns a query builder for PlaylistSong.
func (c *PlaylistSongClient) Query() *PlaylistSongQuery {
	return &PlaylistSongQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePlaylistSong},
		inters: c.Interceptors(),
	}
}

// Get returns a PlaylistSong entity by its id.
func (c *PlaylistSongClient) Get(ctx context.Context, id string) (*PlaylistSong, error) {
	return c.Query().Where(playlistsong.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PlaylistSongClient) GetX(ctx context.Context, id string) *PlaylistSong {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PlaylistSongClient) Hooks() []Hook {
	return c.hooks.PlaylistSong
}

// Interceptors returns the client interceptors.
func (c *PlaylistSongClient) Interceptors() []Interceptor {
	return c.inters.PlaylistSong
}

func (c *PlaylistSongClient) mutate(ctx context.Context, m *PlaylistSongMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PlaylistSongCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PlaylistSongUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PlaylistSongUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PlaylistSongDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PlaylistSong mutation op: %q", m.Op())
	}
}

// SongClient is a client for the Song schema.
type SongClient struct {
	config
}

// NewSongClient returns a client for the Song from the given config.
func NewSongClient(c config) *SongClient {
	return &SongClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `song.Hooks(f(g(h())))`.
func (c *SongClient) Use(hooks ...Hook) {
	c.hooks.Song = append(c.hooks.Song, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `song.Intercept(f(g(h())))`.
func (c *SongClient) Intercept(interceptors ...Interceptor) {
	c.inters.Song = append(c.inters.Song, interceptors...)
}

// Create returns a builder for creating a Song entity.
func (c *SongClient) Create() *SongCreate {
	mutation := newSongMutation(c.config, OpCreate)
	return &SongCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Song entities.
func (c *SongClient) CreateBulk(builders ...*SongCreate) *SongCreateBulk {
	return &SongCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SongClient) MapCreateBulk(slice any, setFunc func(*SongCreate, int)) *SongCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SongCreateBulk{err: fmt.Errorf("calling to SongClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SongCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SongCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Song.
func (c *SongClient) Update() *SongUpdate {
	mutation := newSongMutation(c.config, OpUpdate)
	return &SongUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SongClient) UpdateOne(_m *Song) *SongUpdateOne {
	mutation := newSongMutation(c.config, OpUpdateOne, withSong(_m))
	return &SongUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SongClient) UpdateOneID(id string) *SongUpdateOne {
	mutation := newSongMutation(c.config, OpUpdateOne, withSongID(id))
	return &SongUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Song.
func (c *SongClient) Delete() *SongDelete {
	mutation := newSongMutation(c.config, OpDelete)
	return &SongDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SongClient) DeleteOne(_m *Song) *SongDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SongClient) DeleteOneID(id string) *SongDeleteOne {
	builder := c.Delete().Where(song.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SongDeleteOne{builder}
}

// Query returns a query builder for Song.
func (c *SongClient) Query() *SongQuery {
	return &SongQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSong},
		inters: c.Interceptors(),
	}
}

// Get returns a Song entity by its id.
func (c *SongClient) Get(ctx context.Context, id string) (*Song, error) {
	return c.Query().Where(song.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SongClient) GetX(ctx context.Context, id string) *Song {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SongClient) Hooks() []Hook {
	return c.hooks.Song
}

// Interceptors returns the client interceptors.
func (c *SongClient) Interceptors() []Interceptor {
	return c.inters.Song
}

func (c *SongClient) mutate(ctx context.Context, m *SongMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SongCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SongUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SongUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SongDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Song mutation op: %q", m.Op())
	}
}

// SyncLogClient is a client for the SyncLog schema.
type SyncLogClient struct {
	config
}

// NewSyncLogClient returns a client for the SyncLog from the given config.
func NewSyncLogClient(c config) *SyncLogClient {
	return &SyncLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `synclog.Hooks(f(g(h())))`.
func (c *SyncLogClient) Use(hooks ...Hook) {
	c.hooks.SyncLog = append(c.hooks.SyncLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `synclog.Intercept(f(g(h())))`.
func (c *SyncLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.SyncLog = append(c.inters.SyncLog, interceptors...)
}

// Create returns a builder for creating a SyncLog entity.
func (c *SyncLogClient) Create() *SyncLogCreate {
	mutation := newSyncLogMutation(c.config, OpCreate)
	return &SyncLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SyncLog entities.
func (c *SyncLogClient) CreateBulk(builders ...*SyncLogCreate) *SyncLogCreateBulk {
	return &SyncLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SyncLogClient) MapCreateBulk(slice any, setFunc func(*SyncLogCreate, int)) *SyncLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SyncLogCreateBulk{err: fmt.Errorf("calling to SyncLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SyncLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SyncLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SyncLog.
func (c *SyncLogClient) Update() *SyncLogUpdate {
	mutation := newSyncLogMutation(c.config, OpUpdate)
	return &SyncLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SyncLogClient) UpdateOne(_m *SyncLog) *SyncLogUpdateOne {
	mutation := newSyncLogMutation(c.config, OpUpdateOne, withSyncLog(_m))
	return &SyncLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SyncLogClient) UpdateOneID(id string) *SyncLogUpdateOne {
	mutation := newSyncLogMutation(c.config, OpUpdateOne, withSyncLogID(id))
	return &SyncLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SyncLog.
func (c *SyncLogClient) Delete() *SyncLogDelete {
	mutation := newSyncLogMutation(c.config, OpDelete)
	return &SyncLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SyncLogClient) DeleteOne(_m *SyncLog) *SyncLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SyncLogClient) DeleteOneID(id string) *SyncLogDeleteOne {
	builder := c.Delete().Where(synclog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SyncLogDeleteOne{builder}
}

// Query returns a query builder for SyncLog.
func (c *SyncLogClient) Query() *SyncLogQuery {
	return &SyncLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSyncLog},
		inters: c.Interceptors(),
	}
}

// Get returns a SyncLog entity by its id.
func (c *SyncLogClient) Get(ctx context.Context, id string) (*SyncLog, error) {
	return c.Query().Where(synclog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SyncLogClient) GetX(ctx context.Context, id string) *SyncLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SyncLogClient) Hooks() []Hook {
	return c.hooks.SyncLog
}

// Interceptors returns the client interceptors.
func (c *SyncLogClient) Interceptors() []Interceptor {
	return c.inters.SyncLog
}

func (c *SyncLogClient) mutate(ctx context.Context, m *SyncLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SyncLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SyncLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SyncLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SyncLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SyncLog mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id string) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id string) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id string) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id string) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Device, Lyric, Playlist, PlaylistSong, Song, SyncLog, User []ent.Hook
	}
	inters struct {
		Device, Lyric, Playlist, PlaylistSong, Song, SyncLog, User []ent.Interceptor
	}
)
