// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/device"
)

// DeviceCreate is the builder for creating a Device entity.
type DeviceCreate struct {
	config
	mutation *DeviceMutation
	hooks    []Hook
}

// SetDeviceID sets the "device_id" field.
func (_c *DeviceCreate) SetDeviceID(v string) *DeviceCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *DeviceCreate) SetDeviceName(v string) *DeviceCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableDeviceName(v *string) *DeviceCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *DeviceCreate) SetPlatform(v string) *DeviceCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *DeviceCreate) SetNillablePlatform(v *string) *DeviceCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetOsVersion sets the "os_version" field.
func (_c *DeviceCreate) SetOsVersion(v string) *DeviceCreate {
	_c.mutation.SetOsVersion(v)
	return _c
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableOsVersion(v *string) *DeviceCreate {
	if v != nil {
		_c.SetOsVersion(*v)
	}
	return _c
}

// SetClientVersion sets the "client_version" field.
func (_c *DeviceCreate) SetClientVersion(v string) *DeviceCreate {
	_c.mutation.SetClientVersion(v)
	return _c
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableClientVersion(v *string) *DeviceCreate {
	if v != nil {
		_c.SetClientVersion(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DeviceCreate) SetUserID(v string) *DeviceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_c *DeviceCreate) SetLastSyncAt(v time.Time) *DeviceCreate {
	_c.mutation.SetLastSyncAt(v)
	return _c
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableLastSyncAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetLastSyncAt(*v)
	}
	return _c
}

// SetSyncState sets the "sync_state" field.
func (_c *DeviceCreate) SetSyncState(v string) *DeviceCreate {
	_c.mutation.SetSyncState(v)
	return _c
}

// SetNillableSyncState sets the "sync_state" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableSyncState(v *string) *DeviceCreate {
	if v != nil {
		_c.SetSyncState(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceCreate) SetCreatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeviceCreate) SetUpdatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the DeviceMutation object of the builder.
func (_c *DeviceCreate) Mutation() *DeviceMutation {
	return _c.mutation
}

// Save creates the Device in the database.
func (_c *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceCreate) SaveX(ctx context.Context) *Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceCreate) defaults() {
	if _, ok := _c.mutation.DeviceName(); !ok {
		v := device.DefaultDeviceName
		_c.mutation.SetDeviceName(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := device.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.OsVersion(); !ok {
		v := device.DefaultOsVersion
		_c.mutation.SetOsVersion(v)
	}
	if _, ok := _c.mutation.ClientVersion(); !ok {
		v := device.DefaultClientVersion
		_c.mutation.SetClientVersion(v)
	}
	if _, ok := _c.mutation.SyncState(); !ok {
		v := device.DefaultSyncState
		_c.mutation.SetSyncState(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "Device.device_id"`)}
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "device_name", err: errors.New(`ent: missing required field "Device.device_name"`)}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := device.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "Device.device_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Device.platform"`)}
	}
	if _, ok := _c.mutation.OsVersion(); !ok {
		return &ValidationError{Name: "os_version", err: errors.New(`ent: missing required field "Device.os_version"`)}
	}
	if _, ok := _c.mutation.ClientVersion(); !ok {
		return &ValidationError{Name: "client_version", err: errors.New(`ent: missing required field "Device.client_version"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Device.user_id"`)}
	}
	if _, ok := _c.mutation.SyncState(); !ok {
		return &ValidationError{Name: "sync_state", err: errors.New(`ent: missing required field "Device.sync_state"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Device.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Device.updated_at"`)}
	}
	return nil
}

func (_c *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec) {
	var (
		_node = &Device{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(device.Table, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(device.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(device.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.OsVersion(); ok {
		_spec.SetField(device.FieldOsVersion, field.TypeString, value)
		_node.OsVersion = value
	}
	if value, ok := _c.mutation.ClientVersion(); ok {
		_spec.SetField(device.FieldClientVersion, field.TypeString, value)
		_node.ClientVersion = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(device.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.LastSyncAt(); ok {
		_spec.SetField(device.FieldLastSyncAt, field.TypeTime, value)
		_node.LastSyncAt = &value
	}
	if value, ok := _c.mutation.SyncState(); ok {
		_spec.SetField(device.FieldSyncState, field.TypeString, value)
		_node.SyncState = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DeviceCreateBulk is the builder for creating many Device entities in bulk.
type DeviceCreateBulk struct {
	config
	err      error
	builders []*DeviceCreate
}

// Save creates the Device entities in the database.
func (_c *DeviceCreateBulk) Save(ctx context.Context) ([]*Device, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Device, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceCreateBulk) SaveX(ctx context.Context) []*Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
