// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/device"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/predicate"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *DeviceUpdate) SetDeviceName(v string) *DeviceUpdate {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceName(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *DeviceUpdate) SetPlatform(v string) *DeviceUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillablePlatform(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *DeviceUpdate) SetOsVersion(v string) *DeviceUpdate {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableOsVersion(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// SetClientVersion sets the "client_version" field.
func (_u *DeviceUpdate) SetClientVersion(v string) *DeviceUpdate {
	_u.mutation.SetClientVersion(v)
	return _u
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableClientVersion(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetClientVersion(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DeviceUpdate) SetUserID(v string) *DeviceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableUserID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *DeviceUpdate) SetLastSyncAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastSyncAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *DeviceUpdate) ClearLastSyncAt() *DeviceUpdate {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetSyncState sets the "sync_state" field.
func (_u *DeviceUpdate) SetSyncState(v string) *DeviceUpdate {
	_u.mutation.SetSyncState(v)
	return _u
}

// SetNillableSyncState sets the "sync_state" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableSyncState(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetSyncState(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceUpdate) SetCreatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableCreatedAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableUpdatedAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := device.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "Device.device_name": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(device.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(device.FieldOsVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientVersion(); ok {
		_spec.SetField(device.FieldClientVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(device.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(device.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(device.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SyncState(); ok {
		_spec.SetField(device.FieldSyncState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetDeviceName sets the "device_name" field.
func (_u *DeviceUpdateOne) SetDeviceName(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceName(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *DeviceUpdateOne) SetPlatform(v string) *DeviceUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillablePlatform(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *DeviceUpdateOne) SetOsVersion(v string) *DeviceUpdateOne {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableOsVersion(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// SetClientVersion sets the "client_version" field.
func (_u *DeviceUpdateOne) SetClientVersion(v string) *DeviceUpdateOne {
	_u.mutation.SetClientVersion(v)
	return _u
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableClientVersion(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetClientVersion(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DeviceUpdateOne) SetUserID(v string) *DeviceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableUserID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *DeviceUpdateOne) SetLastSyncAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastSyncAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *DeviceUpdateOne) ClearLastSyncAt() *DeviceUpdateOne {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetSyncState sets the "sync_state" field.
func (_u *DeviceUpdateOne) SetSyncState(v string) *DeviceUpdateOne {
	_u.mutation.SetSyncState(v)
	return _u
}

// SetNillableSyncState sets the "sync_state" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableSyncState(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetSyncState(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceUpdateOne) SetCreatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableCreatedAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableUpdatedAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := device.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "Device.device_name": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(device.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(device.FieldOsVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientVersion(); ok {
		_spec.SetField(device.FieldClientVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(device.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(device.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(device.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SyncState(); ok {
		_spec.SetField(device.FieldSyncState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
