// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/lyric"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/predicate"
)

// LyricUpdate is the builder for updating Lyric entities.
type LyricUpdate struct {
	config
	hooks    []Hook
	mutation *LyricMutation
}

// Where appends a list predicates to the LyricUpdate builder.
func (_u *LyricUpdate) Where(ps ...predicate.Lyric) *LyricUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSongID sets the "song_id" field.
func (_u *LyricUpdate) SetSongID(v string) *LyricUpdate {
	_u.mutation.SetSongID(v)
	return _u
}

// SetNillableSongID sets the "song_id" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableSongID(v *string) *LyricUpdate {
	if v != nil {
		_u.SetSongID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *LyricUpdate) SetContent(v string) *LyricUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableContent(v *string) *LyricUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *LyricUpdate) SetType(v string) *LyricUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableType(v *string) *LyricUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *LyricUpdate) SetLanguage(v string) *LyricUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableLanguage(v *string) *LyricUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetOffsetMs sets the "offset_ms" field.
func (_u *LyricUpdate) SetOffsetMs(v int32) *LyricUpdate {
	_u.mutation.ResetOffsetMs()
	_u.mutation.SetOffsetMs(v)
	return _u
}

// SetNillableOffsetMs sets the "offset_ms" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableOffsetMs(v *int32) *LyricUpdate {
	if v != nil {
		_u.SetOffsetMs(*v)
	}
	return _u
}

// AddOffsetMs adds value to the "offset_ms" field.
func (_u *LyricUpdate) AddOffsetMs(v int32) *LyricUpdate {
	_u.mutation.AddOffsetMs(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *LyricUpdate) SetSource(v string) *LyricUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableSource(v *string) *LyricUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *LyricUpdate) SetIsDeleted(v bool) *LyricUpdate {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableIsDeleted(v *bool) *LyricUpdate {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *LyricUpdate) SetVersion(v int64) *LyricUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableVersion(v *int64) *LyricUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *LyricUpdate) AddVersion(v int64) *LyricUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LyricUpdate) SetCreatedAt(v time.Time) *LyricUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableCreatedAt(v *time.Time) *LyricUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LyricUpdate) SetUpdatedAt(v time.Time) *LyricUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *LyricUpdate) SetNillableUpdatedAt(v *time.Time) *LyricUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the LyricMutation object of the builder.
func (_u *LyricUpdate) Mutation() *LyricMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LyricUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LyricUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LyricUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LyricUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LyricUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lyric.Table, lyric.Columns, sqlgraph.NewFieldSpec(lyric.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SongID(); ok {
		_spec.SetField(lyric.FieldSongID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(lyric.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(lyric.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(lyric.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.OffsetMs(); ok {
		_spec.SetField(lyric.FieldOffsetMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedOffsetMs(); ok {
		_spec.AddField(lyric.FieldOffsetMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(lyric.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(lyric.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(lyric.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(lyric.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(lyric.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lyric.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lyric.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LyricUpdateOne is the builder for updating a single Lyric entity.
type LyricUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LyricMutation
}

// SetSongID sets the "song_id" field.
func (_u *LyricUpdateOne) SetSongID(v string) *LyricUpdateOne {
	_u.mutation.SetSongID(v)
	return _u
}

// SetNillableSongID sets the "song_id" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableSongID(v *string) *LyricUpdateOne {
	if v != nil {
		_u.SetSongID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *LyricUpdateOne) SetContent(v string) *LyricUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableContent(v *string) *LyricUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *LyricUpdateOne) SetType(v string) *LyricUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableType(v *string) *LyricUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *LyricUpdateOne) SetLanguage(v string) *LyricUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableLanguage(v *string) *LyricUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetOffsetMs sets the "offset_ms" field.
func (_u *LyricUpdateOne) SetOffsetMs(v int32) *LyricUpdateOne {
	_u.mutation.ResetOffsetMs()
	_u.mutation.SetOffsetMs(v)
	return _u
}

// SetNillableOffsetMs sets the "offset_ms" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableOffsetMs(v *int32) *LyricUpdateOne {
	if v != nil {
		_u.SetOffsetMs(*v)
	}
	return _u
}

// AddOffsetMs adds value to the "offset_ms" field.
func (_u *LyricUpdateOne) AddOffsetMs(v int32) *LyricUpdateOne {
	_u.mutation.AddOffsetMs(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *LyricUpdateOne) SetSource(v string) *LyricUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableSource(v *string) *LyricUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *LyricUpdateOne) SetIsDeleted(v bool) *LyricUpdateOne {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableIsDeleted(v *bool) *LyricUpdateOne {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *LyricUpdateOne) SetVersion(v int64) *LyricUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableVersion(v *int64) *LyricUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *LyricUpdateOne) AddVersion(v int64) *LyricUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LyricUpdateOne) SetCreatedAt(v time.Time) *LyricUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableCreatedAt(v *time.Time) *LyricUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LyricUpdateOne) SetUpdatedAt(v time.Time) *LyricUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *LyricUpdateOne) SetNillableUpdatedAt(v *time.Time) *LyricUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the LyricMutation object of the builder.
func (_u *LyricUpdateOne) Mutation() *LyricMutation {
	return _u.mutation
}

// Where appends a list predicates to the LyricUpdate builder.
func (_u *LyricUpdateOne) Where(ps ...predicate.Lyric) *LyricUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LyricUpdateOne) Select(field string, fields ...string) *LyricUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Lyric entity.
func (_u *LyricUpdateOne) Save(ctx context.Context) (*Lyric, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LyricUpdateOne) SaveX(ctx context.Context) *Lyric {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LyricUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LyricUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LyricUpdateOne) sqlSave(ctx context.Context) (_node *Lyric, err error) {
	_spec := sqlgraph.NewUpdateSpec(lyric.Table, lyric.Columns, sqlgraph.NewFieldSpec(lyric.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Lyric.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lyric.FieldID)
		for _, f := range fields {
			if !lyric.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lyric.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SongID(); ok {
		_spec.SetField(lyric.FieldSongID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(lyric.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(lyric.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(lyric.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.OffsetMs(); ok {
		_spec.SetField(lyric.FieldOffsetMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedOffsetMs(); ok {
		_spec.AddField(lyric.FieldOffsetMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(lyric.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(lyric.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(lyric.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(lyric.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(lyric.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lyric.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Lyric{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lyric.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
