// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/lyric"
)

// Lyric is the model entity for the Lyric schema.
type Lyric struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SongID holds the value of the "song_id" field.
	SongID string `json:"song_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// OffsetMs holds the value of the "offset_ms" field.
	OffsetMs int32 `json:"offset_ms,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Lyric) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lyric.FieldOffsetMs, lyric.FieldVersion:
			values[i] = new(sql.NullInt64)
		case lyric.FieldID, lyric.FieldSongID, lyric.FieldContent, lyric.FieldType, lyric.FieldLanguage, lyric.FieldSource:
			values[i] = new(sql.NullString)
		case lyric.FieldCreatedAt, lyric.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Lyric fields.
func (_m *Lyric) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lyric.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case lyric.FieldSongID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field song_id", values[i])
			} else if value.Valid {
				_m.SongID = value.String
			}
		case lyric.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case lyric.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case lyric.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case lyric.FieldOffsetMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field offset_ms", values[i])
			} else if value.Valid {
				_m.OffsetMs = int32(value.Int64)
			}
		case lyric.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case lyric.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case lyric.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case lyric.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Lyric.
// This includes values selected through modifiers, order, etc.
func (_m *Lyric) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Lyric.
// Note that you need to call Lyric.Unwrap() before calling this method if this Lyric
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Lyric) Update() *LyricUpdateOne {
	return NewLyricClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Lyric entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Lyric) Unwrap() *Lyric {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Lyric is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Lyric) String() string {
	var builder strings.Builder
	builder.WriteString("Lyric(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("song_id=")
	builder.WriteString(_m.SongID)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("offset_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.OffsetMs))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Lyrics is a parsable slice of Lyric.
type Lyrics []*Lyric
