// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/playlistsong"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/predicate"
)

// PlaylistSongUpdate is the builder for updating PlaylistSong entities.
type PlaylistSongUpdate struct {
	config
	hooks    []Hook
	mutation *PlaylistSongMutation
}

// Where appends a list predicates to the PlaylistSongUpdate builder.
func (_u *PlaylistSongUpdate) Where(ps ...predicate.PlaylistSong) *PlaylistSongUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlaylistID sets the "playlist_id" field.
func (_u *PlaylistSongUpdate) SetPlaylistID(v string) *PlaylistSongUpdate {
	_u.mutation.SetPlaylistID(v)
	return _u
}

// SetNillablePlaylistID sets the "playlist_id" field if the given value is not nil.
func (_u *PlaylistSongUpdate) SetNillablePlaylistID(v *string) *PlaylistSongUpdate {
	if v != nil {
		_u.SetPlaylistID(*v)
	}
	return _u
}

// SetSongID sets the "song_id" field.
func (_u *PlaylistSongUpdate) SetSongID(v string) *PlaylistSongUpdate {
	_u.mutation.SetSongID(v)
	return _u
}

// SetNillableSongID sets the "song_id" field if the given value is not nil.
func (_u *PlaylistSongUpdate) SetNillableSongID(v *string) *PlaylistSongUpdate {
	if v != nil {
		_u.SetSongID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *PlaylistSongUpdate) SetPosition(v int32) *PlaylistSongUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *PlaylistSongUpdate) SetNillablePosition(v *int32) *PlaylistSongUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *PlaylistSongUpdate) AddPosition(v int32) *PlaylistSongUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetAddedBy sets the "added_by" field.
func (_u *PlaylistSongUpdate) SetAddedBy(v string) *PlaylistSongUpdate {
	_u.mutation.SetAddedBy(v)
	return _u
}

// SetNillableAddedBy sets the "added_by" field if the given value is not nil.
func (_u *PlaylistSongUpdate) SetNillableAddedBy(v *string) *PlaylistSongUpdate {
	if v != nil {
		_u.SetAddedBy(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PlaylistSongUpdate) SetVersion(v int64) *PlaylistSongUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PlaylistSongUpdate) SetNillableVersion(v *int64) *PlaylistSongUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PlaylistSongUpdate) AddVersion(v int64) *PlaylistSongUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PlaylistSongUpdate) SetCreatedAt(v time.Time) *PlaylistSongUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PlaylistSongUpdate) SetNillableCreatedAt(v *time.Time) *PlaylistSongUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the PlaylistSongMutation object of the builder.
func (_u *PlaylistSongUpdate) Mutation() *PlaylistSongMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlaylistSongUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaylistSongUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlaylistSongUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaylistSongUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PlaylistSongUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(playlistsong.Table, playlistsong.Columns, sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlaylistID(); ok {
		_spec.SetField(playlistsong.FieldPlaylistID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SongID(); ok {
		_spec.SetField(playlistsong.FieldSongID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(playlistsong.FieldPosition, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(playlistsong.FieldPosition, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedBy(); ok {
		_spec.SetField(playlistsong.FieldAddedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(playlistsong.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(playlistsong.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(playlistsong.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playlistsong.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlaylistSongUpdateOne is the builder for updating a single PlaylistSong entity.
type PlaylistSongUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlaylistSongMutation
}

// SetPlaylistID sets the "playlist_id" field.
func (_u *PlaylistSongUpdateOne) SetPlaylistID(v string) *PlaylistSongUpdateOne {
	_u.mutation.SetPlaylistID(v)
	return _u
}

// SetNillablePlaylistID sets the "playlist_id" field if the given value is not nil.
func (_u *PlaylistSongUpdateOne) SetNillablePlaylistID(v *string) *PlaylistSongUpdateOne {
	if v != nil {
		_u.SetPlaylistID(*v)
	}
	return _u
}

// SetSongID sets the "song_id" field.
func (_u *PlaylistSongUpdateOne) SetSongID(v string) *PlaylistSongUpdateOne {
	_u.mutation.SetSongID(v)
	return _u
}

// SetNillableSongID sets the "song_id" field if the given value is not nil.
func (_u *PlaylistSongUpdateOne) SetNillableSongID(v *string) *PlaylistSongUpdateOne {
	if v != nil {
		_u.SetSongID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *PlaylistSongUpdateOne) SetPosition(v int32) *PlaylistSongUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *PlaylistSongUpdateOne) SetNillablePosition(v *int32) *PlaylistSongUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *PlaylistSongUpdateOne) AddPosition(v int32) *PlaylistSongUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetAddedBy sets the "added_by" field.
func (_u *PlaylistSongUpdateOne) SetAddedBy(v string) *PlaylistSongUpdateOne {
	_u.mutation.SetAddedBy(v)
	return _u
}

// SetNillableAddedBy sets the "added_by" field if the given value is not nil.
func (_u *PlaylistSongUpdateOne) SetNillableAddedBy(v *string) *PlaylistSongUpdateOne {
	if v != nil {
		_u.SetAddedBy(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PlaylistSongUpdateOne) SetVersion(v int64) *PlaylistSongUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PlaylistSongUpdateOne) SetNillableVersion(v *int64) *PlaylistSongUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PlaylistSongUpdateOne) AddVersion(v int64) *PlaylistSongUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PlaylistSongUpdateOne) SetCreatedAt(v time.Time) *PlaylistSongUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PlaylistSongUpdateOne) SetNillableCreatedAt(v *time.Time) *PlaylistSongUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the PlaylistSongMutation object of the builder.
func (_u *PlaylistSongUpdateOne) Mutation() *PlaylistSongMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlaylistSongUpdate builder.
func (_u *PlaylistSongUpdateOne) Where(ps ...predicate.PlaylistSong) *PlaylistSongUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlaylistSongUpdateOne) Select(field string, fields ...string) *PlaylistSongUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlaylistSong entity.
func (_u *PlaylistSongUpdateOne) Save(ctx context.Context) (*PlaylistSong, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaylistSongUpdateOne) SaveX(ctx context.Context) *PlaylistSong {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlaylistSongUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaylistSongUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PlaylistSongUpdateOne) sqlSave(ctx context.Context) (_node *PlaylistSong, err error) {
	_spec := sqlgraph.NewUpdateSpec(playlistsong.Table, playlistsong.Columns, sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlaylistSong.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playlistsong.FieldID)
		for _, f := range fields {
			if !playlistsong.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playlistsong.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlaylistID(); ok {
		_spec.SetField(playlistsong.FieldPlaylistID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SongID(); ok {
		_spec.SetField(playlistsong.FieldSongID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(playlistsong.FieldPosition, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(playlistsong.FieldPosition, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedBy(); ok {
		_spec.SetField(playlistsong.FieldAddedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(playlistsong.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(playlistsong.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(playlistsong.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &PlaylistSong{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playlistsong.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
