// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/playlist"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/predicate"
)

// PlaylistUpdate is the builder for updating Playlist entities.
type PlaylistUpdate struct {
	config
	hooks    []Hook
	mutation *PlaylistMutation
}

// Where appends a list predicates to the PlaylistUpdate builder.
func (_u *PlaylistUpdate) Where(ps ...predicate.Playlist) *PlaylistUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PlaylistUpdate) SetName(v string) *PlaylistUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableName(v *string) *PlaylistUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlaylistUpdate) SetDescription(v string) *PlaylistUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableDescription(v *string) *PlaylistUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *PlaylistUpdate) SetCoverURL(v string) *PlaylistUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableCoverURL(v *string) *PlaylistUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *PlaylistUpdate) SetOwnerID(v string) *PlaylistUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableOwnerID(v *string) *PlaylistUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *PlaylistUpdate) SetIsPublic(v bool) *PlaylistUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableIsPublic(v *bool) *PlaylistUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetSongCount sets the "song_count" field.
func (_u *PlaylistUpdate) SetSongCount(v int) *PlaylistUpdate {
	_u.mutation.ResetSongCount()
	_u.mutation.SetSongCount(v)
	return _u
}

// SetNillableSongCount sets the "song_count" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableSongCount(v *int) *PlaylistUpdate {
	if v != nil {
		_u.SetSongCount(*v)
	}
	return _u
}

// AddSongCount adds value to the "song_count" field.
func (_u *PlaylistUpdate) AddSongCount(v int) *PlaylistUpdate {
	_u.mutation.AddSongCount(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *PlaylistUpdate) SetVersion(v int64) *PlaylistUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableVersion(v *int64) *PlaylistUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PlaylistUpdate) AddVersion(v int64) *PlaylistUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PlaylistUpdate) SetCreatedAt(v time.Time) *PlaylistUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableCreatedAt(v *time.Time) *PlaylistUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlaylistUpdate) SetUpdatedAt(v time.Time) *PlaylistUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PlaylistUpdate) SetNillableUpdatedAt(v *time.Time) *PlaylistUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the PlaylistMutation object of the builder.
func (_u *PlaylistUpdate) Mutation() *PlaylistMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlaylistUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaylistUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlaylistUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaylistUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlaylistUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := playlist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Playlist.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := playlist.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Playlist.description": %w`, err)}
		}
	}
	return nil
}

func (_u *PlaylistUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playlist.Table, playlist.Columns, sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(playlist.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(playlist.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(playlist.FieldCoverURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(playlist.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(playlist.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SongCount(); ok {
		_spec.SetField(playlist.FieldSongCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSongCount(); ok {
		_spec.AddField(playlist.FieldSongCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(playlist.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(playlist.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(playlist.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(playlist.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playlist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlaylistUpdateOne is the builder for updating a single Playlist entity.
type PlaylistUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlaylistMutation
}

// SetName sets the "name" field.
func (_u *PlaylistUpdateOne) SetName(v string) *PlaylistUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableName(v *string) *PlaylistUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlaylistUpdateOne) SetDescription(v string) *PlaylistUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableDescription(v *string) *PlaylistUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *PlaylistUpdateOne) SetCoverURL(v string) *PlaylistUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableCoverURL(v *string) *PlaylistUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *PlaylistUpdateOne) SetOwnerID(v string) *PlaylistUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableOwnerID(v *string) *PlaylistUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *PlaylistUpdateOne) SetIsPublic(v bool) *PlaylistUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableIsPublic(v *bool) *PlaylistUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetSongCount sets the "song_count" field.
func (_u *PlaylistUpdateOne) SetSongCount(v int) *PlaylistUpdateOne {
	_u.mutation.ResetSongCount()
	_u.mutation.SetSongCount(v)
	return _u
}

// SetNillableSongCount sets the "song_count" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableSongCount(v *int) *PlaylistUpdateOne {
	if v != nil {
		_u.SetSongCount(*v)
	}
	return _u
}

// AddSongCount adds value to the "song_count" field.
func (_u *PlaylistUpdateOne) AddSongCount(v int) *PlaylistUpdateOne {
	_u.mutation.AddSongCount(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *PlaylistUpdateOne) SetVersion(v int64) *PlaylistUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableVersion(v *int64) *PlaylistUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PlaylistUpdateOne) AddVersion(v int64) *PlaylistUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PlaylistUpdateOne) SetCreatedAt(v time.Time) *PlaylistUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableCreatedAt(v *time.Time) *PlaylistUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlaylistUpdateOne) SetUpdatedAt(v time.Time) *PlaylistUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PlaylistUpdateOne) SetNillableUpdatedAt(v *time.Time) *PlaylistUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the PlaylistMutation object of the builder.
func (_u *PlaylistUpdateOne) Mutation() *PlaylistMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlaylistUpdate builder.
func (_u *PlaylistUpdateOne) Where(ps ...predicate.Playlist) *PlaylistUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlaylistUpdateOne) Select(field string, fields ...string) *PlaylistUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Playlist entity.
func (_u *PlaylistUpdateOne) Save(ctx context.Context) (*Playlist, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaylistUpdateOne) SaveX(ctx context.Context) *Playlist {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlaylistUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaylistUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlaylistUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := playlist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Playlist.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := playlist.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Playlist.description": %w`, err)}
		}
	}
	return nil
}

func (_u *PlaylistUpdateOne) sqlSave(ctx context.Context) (_node *Playlist, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playlist.Table, playlist.Columns, sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Playlist.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playlist.FieldID)
		for _, f := range fields {
			if !playlist.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(playlist.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(playlist.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(playlist.FieldCoverURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(playlist.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(playlist.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SongCount(); ok {
		_spec.SetField(playlist.FieldSongCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSongCount(); ok {
		_spec.AddField(playlist.FieldSongCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(playlist.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(playlist.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(playlist.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(playlist.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Playlist{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playlist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
