// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/playlistsong"
)

// PlaylistSongCreate is the builder for creating a PlaylistSong entity.
type PlaylistSongCreate struct {
	config
	mutation *PlaylistSongMutation
	hooks    []Hook
}

// SetPlaylistID sets the "playlist_id" field.
func (_c *PlaylistSongCreate) SetPlaylistID(v string) *PlaylistSongCreate {
	_c.mutation.SetPlaylistID(v)
	return _c
}

// SetSongID sets the "song_id" field.
func (_c *PlaylistSongCreate) SetSongID(v string) *PlaylistSongCreate {
	_c.mutation.SetSongID(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *PlaylistSongCreate) SetPosition(v int32) *PlaylistSongCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *PlaylistSongCreate) SetNillablePosition(v *int32) *PlaylistSongCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetAddedBy sets the "added_by" field.
func (_c *PlaylistSongCreate) SetAddedBy(v string) *PlaylistSongCreate {
	_c.mutation.SetAddedBy(v)
	return _c
}

// SetNillableAddedBy sets the "added_by" field if the given value is not nil.
func (_c *PlaylistSongCreate) SetNillableAddedBy(v *string) *PlaylistSongCreate {
	if v != nil {
		_c.SetAddedBy(*v)
	}
	return _c
}

// SetAddedAt sets the "added_at" field.
func (_c *PlaylistSongCreate) SetAddedAt(v time.Time) *PlaylistSongCreate {
	_c.mutation.SetAddedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PlaylistSongCreate) SetID(v string) *PlaylistSongCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PlaylistSongMutation object of the builder.
func (_c *PlaylistSongCreate) Mutation() *PlaylistSongMutation {
	return _c.mutation
}

// Save creates the PlaylistSong in the database.
func (_c *PlaylistSongCreate) Save(ctx context.Context) (*PlaylistSong, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlaylistSongCreate) SaveX(ctx context.Context) *PlaylistSong {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaylistSongCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaylistSongCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlaylistSongCreate) defaults() {
	if _, ok := _c.mutation.Position(); !ok {
		v := playlistsong.DefaultPosition
		_c.mutation.SetPosition(v)
	}
	if _, ok := _c.mutation.AddedBy(); !ok {
		v := playlistsong.DefaultAddedBy
		_c.mutation.SetAddedBy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlaylistSongCreate) check() error {
	if _, ok := _c.mutation.PlaylistID(); !ok {
		return &ValidationError{Name: "playlist_id", err: errors.New(`ent: missing required field "PlaylistSong.playlist_id"`)}
	}
	if _, ok := _c.mutation.SongID(); !ok {
		return &ValidationError{Name: "song_id", err: errors.New(`ent: missing required field "PlaylistSong.song_id"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "PlaylistSong.position"`)}
	}
	if _, ok := _c.mutation.AddedBy(); !ok {
		return &ValidationError{Name: "added_by", err: errors.New(`ent: missing required field "PlaylistSong.added_by"`)}
	}
	if _, ok := _c.mutation.AddedAt(); !ok {
		return &ValidationError{Name: "added_at", err: errors.New(`ent: missing required field "PlaylistSong.added_at"`)}
	}
	return nil
}

func (_c *PlaylistSongCreate) sqlSave(ctx context.Context) (*PlaylistSong, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PlaylistSong.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlaylistSongCreate) createSpec() (*PlaylistSong, *sqlgraph.CreateSpec) {
	var (
		_node = &PlaylistSong{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playlistsong.Table, sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PlaylistID(); ok {
		_spec.SetField(playlistsong.FieldPlaylistID, field.TypeString, value)
		_node.PlaylistID = value
	}
	if value, ok := _c.mutation.SongID(); ok {
		_spec.SetField(playlistsong.FieldSongID, field.TypeString, value)
		_node.SongID = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(playlistsong.FieldPosition, field.TypeInt32, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.AddedBy(); ok {
		_spec.SetField(playlistsong.FieldAddedBy, field.TypeString, value)
		_node.AddedBy = value
	}
	if value, ok := _c.mutation.AddedAt(); ok {
		_spec.SetField(playlistsong.FieldAddedAt, field.TypeTime, value)
		_node.AddedAt = value
	}
	return _node, _spec
}

// PlaylistSongCreateBulk is the builder for creating many PlaylistSong entities in bulk.
type PlaylistSongCreateBulk struct {
	config
	err      error
	builders []*PlaylistSongCreate
}

// Save creates the PlaylistSong entities in the database.
func (_c *PlaylistSongCreateBulk) Save(ctx context.Context) ([]*PlaylistSong, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlaylistSong, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlaylistSongMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlaylistSongCreateBulk) SaveX(ctx context.Context) []*PlaylistSong {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaylistSongCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaylistSongCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
