// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/device"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/lyric"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/playlist"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/playlistsong"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/schema"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/song"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/synclog"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescDeviceName is the schema descriptor for device_name field.
	deviceDescDeviceName := deviceFields[1].Descriptor()
	// device.DefaultDeviceName holds the default value on creation for the device_name field.
	device.DefaultDeviceName = deviceDescDeviceName.Default.(string)
	// device.DeviceNameValidator is a validator for the "device_name" field. It is called by the builders before save.
	device.DeviceNameValidator = deviceDescDeviceName.Validators[0].(func(string) error)
	// deviceDescPlatform is the schema descriptor for platform field.
	deviceDescPlatform := deviceFields[2].Descriptor()
	// device.DefaultPlatform holds the default value on creation for the platform field.
	device.DefaultPlatform = deviceDescPlatform.Default.(string)
	// deviceDescOsVersion is the schema descriptor for os_version field.
	deviceDescOsVersion := deviceFields[3].Descriptor()
	// device.DefaultOsVersion holds the default value on creation for the os_version field.
	device.DefaultOsVersion = deviceDescOsVersion.Default.(string)
	// deviceDescClientVersion is the schema descriptor for client_version field.
	deviceDescClientVersion := deviceFields[4].Descriptor()
	// device.DefaultClientVersion holds the default value on creation for the client_version field.
	device.DefaultClientVersion = deviceDescClientVersion.Default.(string)
	// deviceDescSyncState is the schema descriptor for sync_state field.
	deviceDescSyncState := deviceFields[7].Descriptor()
	// device.DefaultSyncState holds the default value on creation for the sync_state field.
	device.DefaultSyncState = deviceDescSyncState.Default.(string)
	lyricFields := schema.Lyric{}.Fields()
	_ = lyricFields
	// lyricDescType is the schema descriptor for type field.
	lyricDescType := lyricFields[3].Descriptor()
	// lyric.DefaultType holds the default value on creation for the type field.
	lyric.DefaultType = lyricDescType.Default.(string)
	// lyricDescLanguage is the schema descriptor for language field.
	lyricDescLanguage := lyricFields[4].Descriptor()
	// lyric.DefaultLanguage holds the default value on creation for the language field.
	lyric.DefaultLanguage = lyricDescLanguage.Default.(string)
	// lyricDescOffsetMs is the schema descriptor for offset_ms field.
	lyricDescOffsetMs := lyricFields[5].Descriptor()
	// lyric.DefaultOffsetMs holds the default value on creation for the offset_ms field.
	lyric.DefaultOffsetMs = lyricDescOffsetMs.Default.(int32)
	// lyricDescSource is the schema descriptor for source field.
	lyricDescSource := lyricFields[6].Descriptor()
	// lyric.DefaultSource holds the default value on creation for the source field.
	lyric.DefaultSource = lyricDescSource.Default.(string)
	// lyricDescVersion is the schema descriptor for version field.
	lyricDescVersion := lyricFields[7].Descriptor()
	// lyric.DefaultVersion holds the default value on creation for the version field.
	lyric.DefaultVersion = lyricDescVersion.Default.(int64)
	playlistFields := schema.Playlist{}.Fields()
	_ = playlistFields
	// playlistDescName is the schema descriptor for name field.
	playlistDescName := playlistFields[1].Descriptor()
	// playlist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	playlist.NameValidator = playlistDescName.Validators[0].(func(string) error)
	// playlistDescDescription is the schema descriptor for description field.
	playlistDescDescription := playlistFields[2].Descriptor()
	// playlist.DefaultDescription holds the default value on creation for the description field.
	playlist.DefaultDescription = playlistDescDescription.Default.(string)
	// playlist.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	playlist.DescriptionValidator = playlistDescDescription.Validators[0].(func(string) error)
	// playlistDescCoverURL is the schema descriptor for cover_url field.
	playlistDescCoverURL := playlistFields[3].Descriptor()
	// playlist.DefaultCoverURL holds the default value on creation for the cover_url field.
	playlist.DefaultCoverURL = playlistDescCoverURL.Default.(string)
	// playlistDescIsPublic is the schema descriptor for is_public field.
	playlistDescIsPublic := playlistFields[5].Descriptor()
	// playlist.DefaultIsPublic holds the default value on creation for the is_public field.
	playlist.DefaultIsPublic = playlistDescIsPublic.Default.(bool)
	// playlistDescSongCount is the schema descriptor for song_count field.
	playlistDescSongCount := playlistFields[6].Descriptor()
	// playlist.DefaultSongCount holds the default value on creation for the song_count field.
	playlist.DefaultSongCount = playlistDescSongCount.Default.(int)
	// playlistDescVersion is the schema descriptor for version field.
	playlistDescVersion := playlistFields[7].Descriptor()
	// playlist.DefaultVersion holds the default value on creation for the version field.
	playlist.DefaultVersion = playlistDescVersion.Default.(int64)
	playlistsongFields := schema.PlaylistSong{}.Fields()
	_ = playlistsongFields
	// playlistsongDescPosition is the schema descriptor for position field.
	playlistsongDescPosition := playlistsongFields[3].Descriptor()
	// playlistsong.DefaultPosition holds the default value on creation for the position field.
	playlistsong.DefaultPosition = playlistsongDescPosition.Default.(int32)
	// playlistsongDescAddedBy is the schema descriptor for added_by field.
	playlistsongDescAddedBy := playlistsongFields[4].Descriptor()
	// playlistsong.DefaultAddedBy holds the default value on creation for the added_by field.
	playlistsong.DefaultAddedBy = playlistsongDescAddedBy.Default.(string)
	songFields := schema.Song{}.Fields()
	_ = songFields
	// songDescTitle is the schema descriptor for title field.
	songDescTitle := songFields[1].Descriptor()
	// song.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	song.TitleValidator = songDescTitle.Validators[0].(func(string) error)
	// songDescArtist is the schema descriptor for artist field.
	songDescArtist := songFields[2].Descriptor()
	// song.DefaultArtist holds the default value on creation for the artist field.
	song.DefaultArtist = songDescArtist.Default.(string)
	// song.ArtistValidator is a validator for the "artist" field. It is called by the builders before save.
	song.ArtistValidator = songDescArtist.Validators[0].(func(string) error)
	// songDescAlbum is the schema descriptor for album field.
	songDescAlbum := songFields[3].Descriptor()
	// song.DefaultAlbum holds the default value on creation for the album field.
	song.DefaultAlbum = songDescAlbum.Default.(string)
	// song.AlbumValidator is a validator for the "album" field. It is called by the builders before save.
	song.AlbumValidator = songDescAlbum.Validators[0].(func(string) error)
	// songDescGenre is the schema descriptor for genre field.
	songDescGenre := songFields[4].Descriptor()
	// song.DefaultGenre holds the default value on creation for the genre field.
	song.DefaultGenre = songDescGenre.Default.(string)
	// song.GenreValidator is a validator for the "genre" field. It is called by the builders before save.
	song.GenreValidator = songDescGenre.Validators[0].(func(string) error)
	// songDescTrackNumber is the schema descriptor for track_number field.
	songDescTrackNumber := songFields[5].Descriptor()
	// song.DefaultTrackNumber holds the default value on creation for the track_number field.
	song.DefaultTrackNumber = songDescTrackNumber.Default.(int32)
	// songDescDiscNumber is the schema descriptor for disc_number field.
	songDescDiscNumber := songFields[6].Descriptor()
	// song.DefaultDiscNumber holds the default value on creation for the disc_number field.
	song.DefaultDiscNumber = songDescDiscNumber.Default.(int32)
	// songDescDurationMs is the schema descriptor for duration_ms field.
	songDescDurationMs := songFields[7].Descriptor()
	// song.DefaultDurationMs holds the default value on creation for the duration_ms field.
	song.DefaultDurationMs = songDescDurationMs.Default.(int32)
	// songDescYear is the schema descriptor for year field.
	songDescYear := songFields[8].Descriptor()
	// song.DefaultYear holds the default value on creation for the year field.
	song.DefaultYear = songDescYear.Default.(int32)
	// songDescFileName is the schema descriptor for file_name field.
	songDescFileName := songFields[9].Descriptor()
	// song.DefaultFileName holds the default value on creation for the file_name field.
	song.DefaultFileName = songDescFileName.Default.(string)
	// song.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	song.FileNameValidator = songDescFileName.Validators[0].(func(string) error)
	// songDescFileSize is the schema descriptor for file_size field.
	songDescFileSize := songFields[10].Descriptor()
	// song.DefaultFileSize holds the default value on creation for the file_size field.
	song.DefaultFileSize = songDescFileSize.Default.(int64)
	// songDescFileHash is the schema descriptor for file_hash field.
	songDescFileHash := songFields[11].Descriptor()
	// song.DefaultFileHash holds the default value on creation for the file_hash field.
	song.DefaultFileHash = songDescFileHash.Default.(string)
	// song.FileHashValidator is a validator for the "file_hash" field. It is called by the builders before save.
	song.FileHashValidator = songDescFileHash.Validators[0].(func(string) error)
	// songDescMimeType is the schema descriptor for mime_type field.
	songDescMimeType := songFields[12].Descriptor()
	// song.DefaultMimeType holds the default value on creation for the mime_type field.
	song.DefaultMimeType = songDescMimeType.Default.(string)
	// song.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	song.MimeTypeValidator = songDescMimeType.Validators[0].(func(string) error)
	// songDescBitrate is the schema descriptor for bitrate field.
	songDescBitrate := songFields[13].Descriptor()
	// song.DefaultBitrate holds the default value on creation for the bitrate field.
	song.DefaultBitrate = songDescBitrate.Default.(int32)
	// songDescSampleRate is the schema descriptor for sample_rate field.
	songDescSampleRate := songFields[14].Descriptor()
	// song.DefaultSampleRate holds the default value on creation for the sample_rate field.
	song.DefaultSampleRate = songDescSampleRate.Default.(int32)
	// songDescSource is the schema descriptor for source field.
	songDescSource := songFields[15].Descriptor()
	// song.DefaultSource holds the default value on creation for the source field.
	song.DefaultSource = songDescSource.Default.(string)
	// songDescFileStatus is the schema descriptor for file_status field.
	songDescFileStatus := songFields[16].Descriptor()
	// song.DefaultFileStatus holds the default value on creation for the file_status field.
	song.DefaultFileStatus = songDescFileStatus.Default.(string)
	// songDescOwnerID is the schema descriptor for owner_id field.
	songDescOwnerID := songFields[17].Descriptor()
	// song.DefaultOwnerID holds the default value on creation for the owner_id field.
	song.DefaultOwnerID = songDescOwnerID.Default.(string)
	// songDescVersion is the schema descriptor for version field.
	songDescVersion := songFields[18].Descriptor()
	// song.DefaultVersion holds the default value on creation for the version field.
	song.DefaultVersion = songDescVersion.Default.(int64)
	// songDescIsDeleted is the schema descriptor for is_deleted field.
	songDescIsDeleted := songFields[19].Descriptor()
	// song.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	song.DefaultIsDeleted = songDescIsDeleted.Default.(bool)
	synclogFields := schema.SyncLog{}.Fields()
	_ = synclogFields
	// synclogDescAcked is the schema descriptor for acked field.
	synclogDescAcked := synclogFields[7].Descriptor()
	// synclog.DefaultAcked holds the default value on creation for the acked field.
	synclog.DefaultAcked = synclogDescAcked.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[2].Descriptor()
	// user.DefaultDisplayName holds the default value on creation for the display_name field.
	user.DefaultDisplayName = userDescDisplayName.Default.(string)
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
}
