// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/song"
)

// SongCreate is the builder for creating a Song entity.
type SongCreate struct {
	config
	mutation *SongMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *SongCreate) SetTitle(v string) *SongCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetArtist sets the "artist" field.
func (_c *SongCreate) SetArtist(v string) *SongCreate {
	_c.mutation.SetArtist(v)
	return _c
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_c *SongCreate) SetNillableArtist(v *string) *SongCreate {
	if v != nil {
		_c.SetArtist(*v)
	}
	return _c
}

// SetAlbum sets the "album" field.
func (_c *SongCreate) SetAlbum(v string) *SongCreate {
	_c.mutation.SetAlbum(v)
	return _c
}

// SetNillableAlbum sets the "album" field if the given value is not nil.
func (_c *SongCreate) SetNillableAlbum(v *string) *SongCreate {
	if v != nil {
		_c.SetAlbum(*v)
	}
	return _c
}

// SetGenre sets the "genre" field.
func (_c *SongCreate) SetGenre(v string) *SongCreate {
	_c.mutation.SetGenre(v)
	return _c
}

// SetNillableGenre sets the "genre" field if the given value is not nil.
func (_c *SongCreate) SetNillableGenre(v *string) *SongCreate {
	if v != nil {
		_c.SetGenre(*v)
	}
	return _c
}

// SetTrackNumber sets the "track_number" field.
func (_c *SongCreate) SetTrackNumber(v int32) *SongCreate {
	_c.mutation.SetTrackNumber(v)
	return _c
}

// SetNillableTrackNumber sets the "track_number" field if the given value is not nil.
func (_c *SongCreate) SetNillableTrackNumber(v *int32) *SongCreate {
	if v != nil {
		_c.SetTrackNumber(*v)
	}
	return _c
}

// SetDiscNumber sets the "disc_number" field.
func (_c *SongCreate) SetDiscNumber(v int32) *SongCreate {
	_c.mutation.SetDiscNumber(v)
	return _c
}

// SetNillableDiscNumber sets the "disc_number" field if the given value is not nil.
func (_c *SongCreate) SetNillableDiscNumber(v *int32) *SongCreate {
	if v != nil {
		_c.SetDiscNumber(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *SongCreate) SetDurationMs(v int32) *SongCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *SongCreate) SetNillableDurationMs(v *int32) *SongCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetYear sets the "year" field.
func (_c *SongCreate) SetYear(v int32) *SongCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_c *SongCreate) SetNillableYear(v *int32) *SongCreate {
	if v != nil {
		_c.SetYear(*v)
	}
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *SongCreate) SetFileName(v string) *SongCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_c *SongCreate) SetNillableFileName(v *string) *SongCreate {
	if v != nil {
		_c.SetFileName(*v)
	}
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *SongCreate) SetFileSize(v int64) *SongCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *SongCreate) SetNillableFileSize(v *int64) *SongCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetFileHash sets the "file_hash" field.
func (_c *SongCreate) SetFileHash(v string) *SongCreate {
	_c.mutation.SetFileHash(v)
	return _c
}

// SetNillableFileHash sets the "file_hash" field if the given value is not nil.
func (_c *SongCreate) SetNillableFileHash(v *string) *SongCreate {
	if v != nil {
		_c.SetFileHash(*v)
	}
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *SongCreate) SetMimeType(v string) *SongCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *SongCreate) SetNillableMimeType(v *string) *SongCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetBitrate sets the "bitrate" field.
func (_c *SongCreate) SetBitrate(v int32) *SongCreate {
	_c.mutation.SetBitrate(v)
	return _c
}

// SetNillableBitrate sets the "bitrate" field if the given value is not nil.
func (_c *SongCreate) SetNillableBitrate(v *int32) *SongCreate {
	if v != nil {
		_c.SetBitrate(*v)
	}
	return _c
}

// SetSampleRate sets the "sample_rate" field.
func (_c *SongCreate) SetSampleRate(v int32) *SongCreate {
	_c.mutation.SetSampleRate(v)
	return _c
}

// SetNillableSampleRate sets the "sample_rate" field if the given value is not nil.
func (_c *SongCreate) SetNillableSampleRate(v *int32) *SongCreate {
	if v != nil {
		_c.SetSampleRate(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *SongCreate) SetSource(v string) *SongCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SongCreate) SetNillableSource(v *string) *SongCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetFileStatus sets the "file_status" field.
func (_c *SongCreate) SetFileStatus(v string) *SongCreate {
	_c.mutation.SetFileStatus(v)
	return _c
}

// SetNillableFileStatus sets the "file_status" field if the given value is not nil.
func (_c *SongCreate) SetNillableFileStatus(v *string) *SongCreate {
	if v != nil {
		_c.SetFileStatus(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *SongCreate) SetOwnerID(v string) *SongCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *SongCreate) SetNillableOwnerID(v *string) *SongCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *SongCreate) SetVersion(v int64) *SongCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *SongCreate) SetNillableVersion(v *int64) *SongCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetIsDeleted sets the "is_deleted" field.
func (_c *SongCreate) SetIsDeleted(v bool) *SongCreate {
	_c.mutation.SetIsDeleted(v)
	return _c
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_c *SongCreate) SetNillableIsDeleted(v *bool) *SongCreate {
	if v != nil {
		_c.SetIsDeleted(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SongCreate) SetCreatedAt(v time.Time) *SongCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SongCreate) SetUpdatedAt(v time.Time) *SongCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SongCreate) SetID(v string) *SongCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SongMutation object of the builder.
func (_c *SongCreate) Mutation() *SongMutation {
	return _c.mutation
}

// Save creates the Song in the database.
func (_c *SongCreate) Save(ctx context.Context) (*Song, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SongCreate) SaveX(ctx context.Context) *Song {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SongCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SongCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SongCreate) defaults() {
	if _, ok := _c.mutation.Artist(); !ok {
		v := song.DefaultArtist
		_c.mutation.SetArtist(v)
	}
	if _, ok := _c.mutation.Album(); !ok {
		v := song.DefaultAlbum
		_c.mutation.SetAlbum(v)
	}
	if _, ok := _c.mutation.Genre(); !ok {
		v := song.DefaultGenre
		_c.mutation.SetGenre(v)
	}
	if _, ok := _c.mutation.TrackNumber(); !ok {
		v := song.DefaultTrackNumber
		_c.mutation.SetTrackNumber(v)
	}
	if _, ok := _c.mutation.DiscNumber(); !ok {
		v := song.DefaultDiscNumber
		_c.mutation.SetDiscNumber(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := song.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.Year(); !ok {
		v := song.DefaultYear
		_c.mutation.SetYear(v)
	}
	if _, ok := _c.mutation.FileName(); !ok {
		v := song.DefaultFileName
		_c.mutation.SetFileName(v)
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		v := song.DefaultFileSize
		_c.mutation.SetFileSize(v)
	}
	if _, ok := _c.mutation.FileHash(); !ok {
		v := song.DefaultFileHash
		_c.mutation.SetFileHash(v)
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		v := song.DefaultMimeType
		_c.mutation.SetMimeType(v)
	}
	if _, ok := _c.mutation.Bitrate(); !ok {
		v := song.DefaultBitrate
		_c.mutation.SetBitrate(v)
	}
	if _, ok := _c.mutation.SampleRate(); !ok {
		v := song.DefaultSampleRate
		_c.mutation.SetSampleRate(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := song.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.FileStatus(); !ok {
		v := song.DefaultFileStatus
		_c.mutation.SetFileStatus(v)
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		v := song.DefaultOwnerID
		_c.mutation.SetOwnerID(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := song.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		v := song.DefaultIsDeleted
		_c.mutation.SetIsDeleted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SongCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Song.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := song.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Song.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Artist(); !ok {
		return &ValidationError{Name: "artist", err: errors.New(`ent: missing required field "Song.artist"`)}
	}
	if v, ok := _c.mutation.Artist(); ok {
		if err := song.ArtistValidator(v); err != nil {
			return &ValidationError{Name: "artist", err: fmt.Errorf(`ent: validator failed for field "Song.artist": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Album(); !ok {
		return &ValidationError{Name: "album", err: errors.New(`ent: missing required field "Song.album"`)}
	}
	if v, ok := _c.mutation.Album(); ok {
		if err := song.AlbumValidator(v); err != nil {
			return &ValidationError{Name: "album", err: fmt.Errorf(`ent: validator failed for field "Song.album": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Genre(); !ok {
		return &ValidationError{Name: "genre", err: errors.New(`ent: missing required field "Song.genre"`)}
	}
	if v, ok := _c.mutation.Genre(); ok {
		if err := song.GenreValidator(v); err != nil {
			return &ValidationError{Name: "genre", err: fmt.Errorf(`ent: validator failed for field "Song.genre": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TrackNumber(); !ok {
		return &ValidationError{Name: "track_number", err: errors.New(`ent: missing required field "Song.track_number"`)}
	}
	if _, ok := _c.mutation.DiscNumber(); !ok {
		return &ValidationError{Name: "disc_number", err: errors.New(`ent: missing required field "Song.disc_number"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "Song.duration_ms"`)}
	}
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "Song.year"`)}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "Song.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := song.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Song.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "Song.file_size"`)}
	}
	if _, ok := _c.mutation.FileHash(); !ok {
		return &ValidationError{Name: "file_hash", err: errors.New(`ent: missing required field "Song.file_hash"`)}
	}
	if v, ok := _c.mutation.FileHash(); ok {
		if err := song.FileHashValidator(v); err != nil {
			return &ValidationError{Name: "file_hash", err: fmt.Errorf(`ent: validator failed for field "Song.file_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "Song.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := song.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Song.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Bitrate(); !ok {
		return &ValidationError{Name: "bitrate", err: errors.New(`ent: missing required field "Song.bitrate"`)}
	}
	if _, ok := _c.mutation.SampleRate(); !ok {
		return &ValidationError{Name: "sample_rate", err: errors.New(`ent: missing required field "Song.sample_rate"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Song.source"`)}
	}
	if _, ok := _c.mutation.FileStatus(); !ok {
		return &ValidationError{Name: "file_status", err: errors.New(`ent: missing required field "Song.file_status"`)}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Song.owner_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Song.version"`)}
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "Song.is_deleted"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Song.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Song.updated_at"`)}
	}
	return nil
}

func (_c *SongCreate) sqlSave(ctx context.Context) (*Song, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Song.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SongCreate) createSpec() (*Song, *sqlgraph.CreateSpec) {
	var (
		_node = &Song{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(song.Table, sqlgraph.NewFieldSpec(song.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(song.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Artist(); ok {
		_spec.SetField(song.FieldArtist, field.TypeString, value)
		_node.Artist = value
	}
	if value, ok := _c.mutation.Album(); ok {
		_spec.SetField(song.FieldAlbum, field.TypeString, value)
		_node.Album = value
	}
	if value, ok := _c.mutation.Genre(); ok {
		_spec.SetField(song.FieldGenre, field.TypeString, value)
		_node.Genre = value
	}
	if value, ok := _c.mutation.TrackNumber(); ok {
		_spec.SetField(song.FieldTrackNumber, field.TypeInt32, value)
		_node.TrackNumber = value
	}
	if value, ok := _c.mutation.DiscNumber(); ok {
		_spec.SetField(song.FieldDiscNumber, field.TypeInt32, value)
		_node.DiscNumber = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(song.FieldDurationMs, field.TypeInt32, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(song.FieldYear, field.TypeInt32, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(song.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(song.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.FileHash(); ok {
		_spec.SetField(song.FieldFileHash, field.TypeString, value)
		_node.FileHash = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(song.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.Bitrate(); ok {
		_spec.SetField(song.FieldBitrate, field.TypeInt32, value)
		_node.Bitrate = value
	}
	if value, ok := _c.mutation.SampleRate(); ok {
		_spec.SetField(song.FieldSampleRate, field.TypeInt32, value)
		_node.SampleRate = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(song.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.FileStatus(); ok {
		_spec.SetField(song.FieldFileStatus, field.TypeString, value)
		_node.FileStatus = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(song.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(song.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.IsDeleted(); ok {
		_spec.SetField(song.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(song.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(song.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SongCreateBulk is the builder for creating many Song entities in bulk.
type SongCreateBulk struct {
	config
	err      error
	builders []*SongCreate
}

// Save creates the Song entities in the database.
func (_c *SongCreateBulk) Save(ctx context.Context) ([]*Song, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Song, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SongMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SongCreateBulk) SaveX(ctx context.Context) []*Song {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SongCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SongCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
