// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/predicate"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/song"
)

// SongUpdate is the builder for updating Song entities.
type SongUpdate struct {
	config
	hooks    []Hook
	mutation *SongMutation
}

// Where appends a list predicates to the SongUpdate builder.
func (_u *SongUpdate) Where(ps ...predicate.Song) *SongUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *SongUpdate) SetTitle(v string) *SongUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SongUpdate) SetNillableTitle(v *string) *SongUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetArtist sets the "artist" field.
func (_u *SongUpdate) SetArtist(v string) *SongUpdate {
	_u.mutation.SetArtist(v)
	return _u
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_u *SongUpdate) SetNillableArtist(v *string) *SongUpdate {
	if v != nil {
		_u.SetArtist(*v)
	}
	return _u
}

// SetAlbum sets the "album" field.
func (_u *SongUpdate) SetAlbum(v string) *SongUpdate {
	_u.mutation.SetAlbum(v)
	return _u
}

// SetNillableAlbum sets the "album" field if the given value is not nil.
func (_u *SongUpdate) SetNillableAlbum(v *string) *SongUpdate {
	if v != nil {
		_u.SetAlbum(*v)
	}
	return _u
}

// SetGenre sets the "genre" field.
func (_u *SongUpdate) SetGenre(v string) *SongUpdate {
	_u.mutation.SetGenre(v)
	return _u
}

// SetNillableGenre sets the "genre" field if the given value is not nil.
func (_u *SongUpdate) SetNillableGenre(v *string) *SongUpdate {
	if v != nil {
		_u.SetGenre(*v)
	}
	return _u
}

// SetTrackNumber sets the "track_number" field.
func (_u *SongUpdate) SetTrackNumber(v int32) *SongUpdate {
	_u.mutation.ResetTrackNumber()
	_u.mutation.SetTrackNumber(v)
	return _u
}

// SetNillableTrackNumber sets the "track_number" field if the given value is not nil.
func (_u *SongUpdate) SetNillableTrackNumber(v *int32) *SongUpdate {
	if v != nil {
		_u.SetTrackNumber(*v)
	}
	return _u
}

// AddTrackNumber adds value to the "track_number" field.
func (_u *SongUpdate) AddTrackNumber(v int32) *SongUpdate {
	_u.mutation.AddTrackNumber(v)
	return _u
}

// SetDiscNumber sets the "disc_number" field.
func (_u *SongUpdate) SetDiscNumber(v int32) *SongUpdate {
	_u.mutation.ResetDiscNumber()
	_u.mutation.SetDiscNumber(v)
	return _u
}

// SetNillableDiscNumber sets the "disc_number" field if the given value is not nil.
func (_u *SongUpdate) SetNillableDiscNumber(v *int32) *SongUpdate {
	if v != nil {
		_u.SetDiscNumber(*v)
	}
	return _u
}

// AddDiscNumber adds value to the "disc_number" field.
func (_u *SongUpdate) AddDiscNumber(v int32) *SongUpdate {
	_u.mutation.AddDiscNumber(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *SongUpdate) SetDurationMs(v int32) *SongUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *SongUpdate) SetNillableDurationMs(v *int32) *SongUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *SongUpdate) AddDurationMs(v int32) *SongUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetYear sets the "year" field.
func (_u *SongUpdate) SetYear(v int32) *SongUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *SongUpdate) SetNillableYear(v *int32) *SongUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *SongUpdate) AddYear(v int32) *SongUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *SongUpdate) SetFileName(v string) *SongUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *SongUpdate) SetNillableFileName(v *string) *SongUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *SongUpdate) SetFileSize(v int64) *SongUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *SongUpdate) SetNillableFileSize(v *int64) *SongUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *SongUpdate) AddFileSize(v int64) *SongUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetFileHash sets the "file_hash" field.
func (_u *SongUpdate) SetFileHash(v string) *SongUpdate {
	_u.mutation.SetFileHash(v)
	return _u
}

// SetNillableFileHash sets the "file_hash" field if the given value is not nil.
func (_u *SongUpdate) SetNillableFileHash(v *string) *SongUpdate {
	if v != nil {
		_u.SetFileHash(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *SongUpdate) SetMimeType(v string) *SongUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *SongUpdate) SetNillableMimeType(v *string) *SongUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetBitrate sets the "bitrate" field.
func (_u *SongUpdate) SetBitrate(v int32) *SongUpdate {
	_u.mutation.ResetBitrate()
	_u.mutation.SetBitrate(v)
	return _u
}

// SetNillableBitrate sets the "bitrate" field if the given value is not nil.
func (_u *SongUpdate) SetNillableBitrate(v *int32) *SongUpdate {
	if v != nil {
		_u.SetBitrate(*v)
	}
	return _u
}

// AddBitrate adds value to the "bitrate" field.
func (_u *SongUpdate) AddBitrate(v int32) *SongUpdate {
	_u.mutation.AddBitrate(v)
	return _u
}

// SetSampleRate sets the "sample_rate" field.
func (_u *SongUpdate) SetSampleRate(v int32) *SongUpdate {
	_u.mutation.ResetSampleRate()
	_u.mutation.SetSampleRate(v)
	return _u
}

// SetNillableSampleRate sets the "sample_rate" field if the given value is not nil.
func (_u *SongUpdate) SetNillableSampleRate(v *int32) *SongUpdate {
	if v != nil {
		_u.SetSampleRate(*v)
	}
	return _u
}

// AddSampleRate adds value to the "sample_rate" field.
func (_u *SongUpdate) AddSampleRate(v int32) *SongUpdate {
	_u.mutation.AddSampleRate(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *SongUpdate) SetSource(v string) *SongUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SongUpdate) SetNillableSource(v *string) *SongUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetFileStatus sets the "file_status" field.
func (_u *SongUpdate) SetFileStatus(v string) *SongUpdate {
	_u.mutation.SetFileStatus(v)
	return _u
}

// SetNillableFileStatus sets the "file_status" field if the given value is not nil.
func (_u *SongUpdate) SetNillableFileStatus(v *string) *SongUpdate {
	if v != nil {
		_u.SetFileStatus(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *SongUpdate) SetOwnerID(v string) *SongUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *SongUpdate) SetNillableOwnerID(v *string) *SongUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *SongUpdate) SetIsDeleted(v bool) *SongUpdate {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *SongUpdate) SetNillableIsDeleted(v *bool) *SongUpdate {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SongUpdate) SetVersion(v int64) *SongUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SongUpdate) SetNillableVersion(v *int64) *SongUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SongUpdate) AddVersion(v int64) *SongUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SongUpdate) SetCreatedAt(v time.Time) *SongUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SongUpdate) SetNillableCreatedAt(v *time.Time) *SongUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SongUpdate) SetUpdatedAt(v time.Time) *SongUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SongUpdate) SetNillableUpdatedAt(v *time.Time) *SongUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the SongMutation object of the builder.
func (_u *SongUpdate) Mutation() *SongMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SongUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SongUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SongUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SongUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SongUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := song.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Song.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Artist(); ok {
		if err := song.ArtistValidator(v); err != nil {
			return &ValidationError{Name: "artist", err: fmt.Errorf(`ent: validator failed for field "Song.artist": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Album(); ok {
		if err := song.AlbumValidator(v); err != nil {
			return &ValidationError{Name: "album", err: fmt.Errorf(`ent: validator failed for field "Song.album": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Genre(); ok {
		if err := song.GenreValidator(v); err != nil {
			return &ValidationError{Name: "genre", err: fmt.Errorf(`ent: validator failed for field "Song.genre": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := song.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Song.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileHash(); ok {
		if err := song.FileHashValidator(v); err != nil {
			return &ValidationError{Name: "file_hash", err: fmt.Errorf(`ent: validator failed for field "Song.file_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := song.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Song.mime_type": %w`, err)}
		}
	}
	return nil
}

func (_u *SongUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(song.Table, song.Columns, sqlgraph.NewFieldSpec(song.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(song.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Artist(); ok {
		_spec.SetField(song.FieldArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.Album(); ok {
		_spec.SetField(song.FieldAlbum, field.TypeString, value)
	}
	if value, ok := _u.mutation.Genre(); ok {
		_spec.SetField(song.FieldGenre, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrackNumber(); ok {
		_spec.SetField(song.FieldTrackNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTrackNumber(); ok {
		_spec.AddField(song.FieldTrackNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DiscNumber(); ok {
		_spec.SetField(song.FieldDiscNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDiscNumber(); ok {
		_spec.AddField(song.FieldDiscNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(song.FieldDurationMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(song.FieldDurationMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(song.FieldYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(song.FieldYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(song.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(song.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(song.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileHash(); ok {
		_spec.SetField(song.FieldFileHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(song.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bitrate(); ok {
		_spec.SetField(song.FieldBitrate, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedBitrate(); ok {
		_spec.AddField(song.FieldBitrate, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.SampleRate(); ok {
		_spec.SetField(song.FieldSampleRate, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSampleRate(); ok {
		_spec.AddField(song.FieldSampleRate, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(song.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileStatus(); ok {
		_spec.SetField(song.FieldFileStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(song.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(song.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(song.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(song.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(song.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(song.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{song.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SongUpdateOne is the builder for updating a single Song entity.
type SongUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SongMutation
}

// SetTitle sets the "title" field.
func (_u *SongUpdateOne) SetTitle(v string) *SongUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableTitle(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetArtist sets the "artist" field.
func (_u *SongUpdateOne) SetArtist(v string) *SongUpdateOne {
	_u.mutation.SetArtist(v)
	return _u
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableArtist(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetArtist(*v)
	}
	return _u
}

// SetAlbum sets the "album" field.
func (_u *SongUpdateOne) SetAlbum(v string) *SongUpdateOne {
	_u.mutation.SetAlbum(v)
	return _u
}

// SetNillableAlbum sets the "album" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableAlbum(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetAlbum(*v)
	}
	return _u
}

// SetGenre sets the "genre" field.
func (_u *SongUpdateOne) SetGenre(v string) *SongUpdateOne {
	_u.mutation.SetGenre(v)
	return _u
}

// SetNillableGenre sets the "genre" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableGenre(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetGenre(*v)
	}
	return _u
}

// SetTrackNumber sets the "track_number" field.
func (_u *SongUpdateOne) SetTrackNumber(v int32) *SongUpdateOne {
	_u.mutation.ResetTrackNumber()
	_u.mutation.SetTrackNumber(v)
	return _u
}

// SetNillableTrackNumber sets the "track_number" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableTrackNumber(v *int32) *SongUpdateOne {
	if v != nil {
		_u.SetTrackNumber(*v)
	}
	return _u
}

// AddTrackNumber adds value to the "track_number" field.
func (_u *SongUpdateOne) AddTrackNumber(v int32) *SongUpdateOne {
	_u.mutation.AddTrackNumber(v)
	return _u
}

// SetDiscNumber sets the "disc_number" field.
func (_u *SongUpdateOne) SetDiscNumber(v int32) *SongUpdateOne {
	_u.mutation.ResetDiscNumber()
	_u.mutation.SetDiscNumber(v)
	return _u
}

// SetNillableDiscNumber sets the "disc_number" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableDiscNumber(v *int32) *SongUpdateOne {
	if v != nil {
		_u.SetDiscNumber(*v)
	}
	return _u
}

// AddDiscNumber adds value to the "disc_number" field.
func (_u *SongUpdateOne) AddDiscNumber(v int32) *SongUpdateOne {
	_u.mutation.AddDiscNumber(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *SongUpdateOne) SetDurationMs(v int32) *SongUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableDurationMs(v *int32) *SongUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *SongUpdateOne) AddDurationMs(v int32) *SongUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetYear sets the "year" field.
func (_u *SongUpdateOne) SetYear(v int32) *SongUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableYear(v *int32) *SongUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *SongUpdateOne) AddYear(v int32) *SongUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *SongUpdateOne) SetFileName(v string) *SongUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableFileName(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *SongUpdateOne) SetFileSize(v int64) *SongUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableFileSize(v *int64) *SongUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *SongUpdateOne) AddFileSize(v int64) *SongUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetFileHash sets the "file_hash" field.
func (_u *SongUpdateOne) SetFileHash(v string) *SongUpdateOne {
	_u.mutation.SetFileHash(v)
	return _u
}

// SetNillableFileHash sets the "file_hash" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableFileHash(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetFileHash(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *SongUpdateOne) SetMimeType(v string) *SongUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableMimeType(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetBitrate sets the "bitrate" field.
func (_u *SongUpdateOne) SetBitrate(v int32) *SongUpdateOne {
	_u.mutation.ResetBitrate()
	_u.mutation.SetBitrate(v)
	return _u
}

// SetNillableBitrate sets the "bitrate" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableBitrate(v *int32) *SongUpdateOne {
	if v != nil {
		_u.SetBitrate(*v)
	}
	return _u
}

// AddBitrate adds value to the "bitrate" field.
func (_u *SongUpdateOne) AddBitrate(v int32) *SongUpdateOne {
	_u.mutation.AddBitrate(v)
	return _u
}

// SetSampleRate sets the "sample_rate" field.
func (_u *SongUpdateOne) SetSampleRate(v int32) *SongUpdateOne {
	_u.mutation.ResetSampleRate()
	_u.mutation.SetSampleRate(v)
	return _u
}

// SetNillableSampleRate sets the "sample_rate" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableSampleRate(v *int32) *SongUpdateOne {
	if v != nil {
		_u.SetSampleRate(*v)
	}
	return _u
}

// AddSampleRate adds value to the "sample_rate" field.
func (_u *SongUpdateOne) AddSampleRate(v int32) *SongUpdateOne {
	_u.mutation.AddSampleRate(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *SongUpdateOne) SetSource(v string) *SongUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableSource(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetFileStatus sets the "file_status" field.
func (_u *SongUpdateOne) SetFileStatus(v string) *SongUpdateOne {
	_u.mutation.SetFileStatus(v)
	return _u
}

// SetNillableFileStatus sets the "file_status" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableFileStatus(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetFileStatus(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *SongUpdateOne) SetOwnerID(v string) *SongUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableOwnerID(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *SongUpdateOne) SetIsDeleted(v bool) *SongUpdateOne {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableIsDeleted(v *bool) *SongUpdateOne {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SongUpdateOne) SetVersion(v int64) *SongUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableVersion(v *int64) *SongUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SongUpdateOne) AddVersion(v int64) *SongUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SongUpdateOne) SetCreatedAt(v time.Time) *SongUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableCreatedAt(v *time.Time) *SongUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SongUpdateOne) SetUpdatedAt(v time.Time) *SongUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableUpdatedAt(v *time.Time) *SongUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the SongMutation object of the builder.
func (_u *SongUpdateOne) Mutation() *SongMutation {
	return _u.mutation
}

// Where appends a list predicates to the SongUpdate builder.
func (_u *SongUpdateOne) Where(ps ...predicate.Song) *SongUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SongUpdateOne) Select(field string, fields ...string) *SongUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Song entity.
func (_u *SongUpdateOne) Save(ctx context.Context) (*Song, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SongUpdateOne) SaveX(ctx context.Context) *Song {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SongUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SongUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SongUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := song.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Song.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Artist(); ok {
		if err := song.ArtistValidator(v); err != nil {
			return &ValidationError{Name: "artist", err: fmt.Errorf(`ent: validator failed for field "Song.artist": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Album(); ok {
		if err := song.AlbumValidator(v); err != nil {
			return &ValidationError{Name: "album", err: fmt.Errorf(`ent: validator failed for field "Song.album": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Genre(); ok {
		if err := song.GenreValidator(v); err != nil {
			return &ValidationError{Name: "genre", err: fmt.Errorf(`ent: validator failed for field "Song.genre": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := song.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Song.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileHash(); ok {
		if err := song.FileHashValidator(v); err != nil {
			return &ValidationError{Name: "file_hash", err: fmt.Errorf(`ent: validator failed for field "Song.file_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := song.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Song.mime_type": %w`, err)}
		}
	}
	return nil
}

func (_u *SongUpdateOne) sqlSave(ctx context.Context) (_node *Song, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(song.Table, song.Columns, sqlgraph.NewFieldSpec(song.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Song.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, song.FieldID)
		for _, f := range fields {
			if !song.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != song.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(song.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Artist(); ok {
		_spec.SetField(song.FieldArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.Album(); ok {
		_spec.SetField(song.FieldAlbum, field.TypeString, value)
	}
	if value, ok := _u.mutation.Genre(); ok {
		_spec.SetField(song.FieldGenre, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrackNumber(); ok {
		_spec.SetField(song.FieldTrackNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTrackNumber(); ok {
		_spec.AddField(song.FieldTrackNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DiscNumber(); ok {
		_spec.SetField(song.FieldDiscNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDiscNumber(); ok {
		_spec.AddField(song.FieldDiscNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(song.FieldDurationMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(song.FieldDurationMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(song.FieldYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(song.FieldYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(song.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(song.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(song.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileHash(); ok {
		_spec.SetField(song.FieldFileHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(song.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bitrate(); ok {
		_spec.SetField(song.FieldBitrate, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedBitrate(); ok {
		_spec.AddField(song.FieldBitrate, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.SampleRate(); ok {
		_spec.SetField(song.FieldSampleRate, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSampleRate(); ok {
		_spec.AddField(song.FieldSampleRate, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(song.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileStatus(); ok {
		_spec.SetField(song.FieldFileStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(song.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(song.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(song.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(song.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(song.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(song.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Song{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{song.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
