// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/synclog"
)

// SyncLogCreate is the builder for creating a SyncLog entity.
type SyncLogCreate struct {
	config
	mutation *SyncLogMutation
	hooks    []Hook
}

// SetDeviceID sets the "device_id" field.
func (_c *SyncLogCreate) SetDeviceID(v string) *SyncLogCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetEntityType sets the "entity_type" field.
func (_c *SyncLogCreate) SetEntityType(v string) *SyncLogCreate {
	_c.mutation.SetEntityType(v)
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *SyncLogCreate) SetEntityID(v string) *SyncLogCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *SyncLogCreate) SetAction(v string) *SyncLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *SyncLogCreate) SetVersion(v int64) *SyncLogCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetData sets the "data" field.
func (_c *SyncLogCreate) SetData(v []byte) *SyncLogCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *SyncLogCreate) SetTimestamp(v time.Time) *SyncLogCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetAcked sets the "acked" field.
func (_c *SyncLogCreate) SetAcked(v bool) *SyncLogCreate {
	_c.mutation.SetAcked(v)
	return _c
}

// SetNillableAcked sets the "acked" field if the given value is not nil.
func (_c *SyncLogCreate) SetNillableAcked(v *bool) *SyncLogCreate {
	if v != nil {
		_c.SetAcked(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SyncLogCreate) SetID(v string) *SyncLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SyncLogMutation object of the builder.
func (_c *SyncLogCreate) Mutation() *SyncLogMutation {
	return _c.mutation
}

// Save creates the SyncLog in the database.
func (_c *SyncLogCreate) Save(ctx context.Context) (*SyncLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncLogCreate) SaveX(ctx context.Context) *SyncLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncLogCreate) defaults() {
	if _, ok := _c.mutation.Acked(); !ok {
		v := synclog.DefaultAcked
		_c.mutation.SetAcked(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncLogCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "SyncLog.device_id"`)}
	}
	if _, ok := _c.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "SyncLog.entity_type"`)}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "SyncLog.entity_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "SyncLog.action"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SyncLog.version"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "SyncLog.timestamp"`)}
	}
	if _, ok := _c.mutation.Acked(); !ok {
		return &ValidationError{Name: "acked", err: errors.New(`ent: missing required field "SyncLog.acked"`)}
	}
	return nil
}

func (_c *SyncLogCreate) sqlSave(ctx context.Context) (*SyncLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SyncLog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncLogCreate) createSpec() (*SyncLog, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(synclog.Table, sqlgraph.NewFieldSpec(synclog.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(synclog.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.EntityType(); ok {
		_spec.SetField(synclog.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := _c.mutation.EntityID(); ok {
		_spec.SetField(synclog.FieldEntityID, field.TypeString, value)
		_node.EntityID = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(synclog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(synclog.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(synclog.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(synclog.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Acked(); ok {
		_spec.SetField(synclog.FieldAcked, field.TypeBool, value)
		_node.Acked = value
	}
	return _node, _spec
}

// SyncLogCreateBulk is the builder for creating many SyncLog entities in bulk.
type SyncLogCreateBulk struct {
	config
	err      error
	builders []*SyncLogCreate
}

// Save creates the SyncLog entities in the database.
func (_c *SyncLogCreateBulk) Save(ctx context.Context) ([]*SyncLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncLogCreateBulk) SaveX(ctx context.Context) []*SyncLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
