// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/predicate"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/synclog"
)

// SyncLogUpdate is the builder for updating SyncLog entities.
type SyncLogUpdate struct {
	config
	hooks    []Hook
	mutation *SyncLogMutation
}

// Where appends a list predicates to the SyncLogUpdate builder.
func (_u *SyncLogUpdate) Where(ps ...predicate.SyncLog) *SyncLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *SyncLogUpdate) SetDeviceID(v string) *SyncLogUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *SyncLogUpdate) SetNillableDeviceID(v *string) *SyncLogUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *SyncLogUpdate) SetEntityType(v string) *SyncLogUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *SyncLogUpdate) SetNillableEntityType(v *string) *SyncLogUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *SyncLogUpdate) SetEntityID(v string) *SyncLogUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *SyncLogUpdate) SetNillableEntityID(v *string) *SyncLogUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *SyncLogUpdate) SetAction(v string) *SyncLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SyncLogUpdate) SetNillableAction(v *string) *SyncLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SyncLogUpdate) SetVersion(v int64) *SyncLogUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SyncLogUpdate) SetNillableVersion(v *int64) *SyncLogUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SyncLogUpdate) AddVersion(v int64) *SyncLogUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetData sets the "data" field.
func (_u *SyncLogUpdate) SetData(v []byte) *SyncLogUpdate {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *SyncLogUpdate) ClearData() *SyncLogUpdate {
	_u.mutation.ClearData()
	return _u
}

// SetAcked sets the "acked" field.
func (_u *SyncLogUpdate) SetAcked(v bool) *SyncLogUpdate {
	_u.mutation.SetAcked(v)
	return _u
}

// SetNillableAcked sets the "acked" field if the given value is not nil.
func (_u *SyncLogUpdate) SetNillableAcked(v *bool) *SyncLogUpdate {
	if v != nil {
		_u.SetAcked(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *SyncLogUpdate) SetTimestamp(v time.Time) *SyncLogUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *SyncLogUpdate) SetNillableTimestamp(v *time.Time) *SyncLogUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the SyncLogMutation object of the builder.
func (_u *SyncLogUpdate) Mutation() *SyncLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SyncLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(synclog.Table, synclog.Columns, sqlgraph.NewFieldSpec(synclog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(synclog.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(synclog.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(synclog.FieldEntityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(synclog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(synclog.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(synclog.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(synclog.FieldData, field.TypeBytes, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(synclog.FieldData, field.TypeBytes)
	}
	if value, ok := _u.mutation.Acked(); ok {
		_spec.SetField(synclog.FieldAcked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(synclog.FieldTimestamp, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{synclog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncLogUpdateOne is the builder for updating a single SyncLog entity.
type SyncLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncLogMutation
}

// SetDeviceID sets the "device_id" field.
func (_u *SyncLogUpdateOne) SetDeviceID(v string) *SyncLogUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *SyncLogUpdateOne) SetNillableDeviceID(v *string) *SyncLogUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *SyncLogUpdateOne) SetEntityType(v string) *SyncLogUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *SyncLogUpdateOne) SetNillableEntityType(v *string) *SyncLogUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *SyncLogUpdateOne) SetEntityID(v string) *SyncLogUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *SyncLogUpdateOne) SetNillableEntityID(v *string) *SyncLogUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *SyncLogUpdateOne) SetAction(v string) *SyncLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SyncLogUpdateOne) SetNillableAction(v *string) *SyncLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SyncLogUpdateOne) SetVersion(v int64) *SyncLogUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SyncLogUpdateOne) SetNillableVersion(v *int64) *SyncLogUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SyncLogUpdateOne) AddVersion(v int64) *SyncLogUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetData sets the "data" field.
func (_u *SyncLogUpdateOne) SetData(v []byte) *SyncLogUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *SyncLogUpdateOne) ClearData() *SyncLogUpdateOne {
	_u.mutation.ClearData()
	return _u
}

// SetAcked sets the "acked" field.
func (_u *SyncLogUpdateOne) SetAcked(v bool) *SyncLogUpdateOne {
	_u.mutation.SetAcked(v)
	return _u
}

// SetNillableAcked sets the "acked" field if the given value is not nil.
func (_u *SyncLogUpdateOne) SetNillableAcked(v *bool) *SyncLogUpdateOne {
	if v != nil {
		_u.SetAcked(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *SyncLogUpdateOne) SetTimestamp(v time.Time) *SyncLogUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *SyncLogUpdateOne) SetNillableTimestamp(v *time.Time) *SyncLogUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the SyncLogMutation object of the builder.
func (_u *SyncLogUpdateOne) Mutation() *SyncLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the SyncLogUpdate builder.
func (_u *SyncLogUpdateOne) Where(ps ...predicate.SyncLog) *SyncLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncLogUpdateOne) Select(field string, fields ...string) *SyncLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncLog entity.
func (_u *SyncLogUpdateOne) Save(ctx context.Context) (*SyncLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncLogUpdateOne) SaveX(ctx context.Context) *SyncLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SyncLogUpdateOne) sqlSave(ctx context.Context) (_node *SyncLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(synclog.Table, synclog.Columns, sqlgraph.NewFieldSpec(synclog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, synclog.FieldID)
		for _, f := range fields {
			if !synclog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != synclog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(synclog.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(synclog.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(synclog.FieldEntityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(synclog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(synclog.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(synclog.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(synclog.FieldData, field.TypeBytes, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(synclog.FieldData, field.TypeBytes)
	}
	if value, ok := _u.mutation.Acked(); ok {
		_spec.SetField(synclog.FieldAcked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(synclog.FieldTimestamp, field.TypeTime, value)
	}
	_node = &SyncLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{synclog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
