// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// Lyric is the predicate function for lyric builders.
type Lyric func(*sql.Selector)

// Playlist is the predicate function for playlist builders.
type Playlist func(*sql.Selector)

// PlaylistSong is the predicate function for playlistsong builders.
type PlaylistSong func(*sql.Selector)

// Song is the predicate function for song builders.
type Song func(*sql.Selector)

// SyncLog is the predicate function for synclog builders.
type SyncLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
