// Code generated by ent, DO NOT EDIT.

package playlistsong

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the playlistsong type in the database.
	Label = "playlist_song"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlaylistID holds the string denoting the playlist_id field in the database.
	FieldPlaylistID = "playlist_id"
	// FieldSongID holds the string denoting the song_id field in the database.
	FieldSongID = "song_id"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldAddedBy holds the string denoting the added_by field in the database.
	FieldAddedBy = "added_by"
	// FieldAddedAt holds the string denoting the added_at field in the database.
	FieldAddedAt = "added_at"
	// Table holds the table name of the playlistsong in the database.
	Table = "playlist_songs"
)

// Columns holds all SQL columns for playlistsong fields.
var Columns = []string{
	FieldID,
	FieldPlaylistID,
	FieldSongID,
	FieldPosition,
	FieldAddedBy,
	FieldAddedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPosition holds the default value on creation for the "position" field.
	DefaultPosition int32
	// DefaultAddedBy holds the default value on creation for the "added_by" field.
	DefaultAddedBy string
)

// OrderOption defines the ordering options for the PlaylistSong queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlaylistID orders the results by the playlist_id field.
func ByPlaylistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaylistID, opts...).ToFunc()
}

// BySongID orders the results by the song_id field.
func BySongID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSongID, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByAddedBy orders the results by the added_by field.
func ByAddedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddedBy, opts...).ToFunc()
}

// ByAddedAt orders the results by the added_at field.
func ByAddedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddedAt, opts...).ToFunc()
}
