// Code generated by ent, DO NOT EDIT.

package playlistsong

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldContainsFold(FieldID, id))
}

// PlaylistID applies equality check predicate on the "playlist_id" field. It's identical to PlaylistIDEQ.
func PlaylistID(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldPlaylistID, v))
}

// SongID applies equality check predicate on the "song_id" field. It's identical to SongIDEQ.
func SongID(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldSongID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int32) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldPosition, v))
}

// AddedBy applies equality check predicate on the "added_by" field. It's identical to AddedByEQ.
func AddedBy(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldAddedBy, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldCreatedAt, v))
}

// PlaylistIDEQ applies the EQ predicate on the "playlist_id" field.
func PlaylistIDEQ(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldPlaylistID, v))
}

// PlaylistIDNEQ applies the NEQ predicate on the "playlist_id" field.
func PlaylistIDNEQ(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldPlaylistID, v))
}

// PlaylistIDIn applies the In predicate on the "playlist_id" field.
func PlaylistIDIn(vs ...string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldPlaylistID, vs...))
}

// PlaylistIDNotIn applies the NotIn predicate on the "playlist_id" field.
func PlaylistIDNotIn(vs ...string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldPlaylistID, vs...))
}

// PlaylistIDGT applies the GT predicate on the "playlist_id" field.
func PlaylistIDGT(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldPlaylistID, v))
}

// PlaylistIDGTE applies the GTE predicate on the "playlist_id" field.
func PlaylistIDGTE(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldPlaylistID, v))
}

// PlaylistIDLT applies the LT predicate on the "playlist_id" field.
func PlaylistIDLT(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldPlaylistID, v))
}

// PlaylistIDLTE applies the LTE predicate on the "playlist_id" field.
func PlaylistIDLTE(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldPlaylistID, v))
}

// PlaylistIDContains applies the Contains predicate on the "playlist_id" field.
func PlaylistIDContains(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldContains(FieldPlaylistID, v))
}

// PlaylistIDHasPrefix applies the HasPrefix predicate on the "playlist_id" field.
func PlaylistIDHasPrefix(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldHasPrefix(FieldPlaylistID, v))
}

// PlaylistIDHasSuffix applies the HasSuffix predicate on the "playlist_id" field.
func PlaylistIDHasSuffix(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldHasSuffix(FieldPlaylistID, v))
}

// PlaylistIDEqualFold applies the EqualFold predicate on the "playlist_id" field.
func PlaylistIDEqualFold(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEqualFold(FieldPlaylistID, v))
}

// PlaylistIDContainsFold applies the ContainsFold predicate on the "playlist_id" field.
func PlaylistIDContainsFold(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldContainsFold(FieldPlaylistID, v))
}

// SongIDEQ applies the EQ predicate on the "song_id" field.
func SongIDEQ(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldSongID, v))
}

// SongIDNEQ applies the NEQ predicate on the "song_id" field.
func SongIDNEQ(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldSongID, v))
}

// SongIDIn applies the In predicate on the "song_id" field.
func SongIDIn(vs ...string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldSongID, vs...))
}

// SongIDNotIn applies the NotIn predicate on the "song_id" field.
func SongIDNotIn(vs ...string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldSongID, vs...))
}

// SongIDGT applies the GT predicate on the "song_id" field.
func SongIDGT(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldSongID, v))
}

// SongIDGTE applies the GTE predicate on the "song_id" field.
func SongIDGTE(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldSongID, v))
}

// SongIDLT applies the LT predicate on the "song_id" field.
func SongIDLT(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldSongID, v))
}

// SongIDLTE applies the LTE predicate on the "song_id" field.
func SongIDLTE(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldSongID, v))
}

// SongIDContains applies the Contains predicate on the "song_id" field.
func SongIDContains(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldContains(FieldSongID, v))
}

// SongIDHasPrefix applies the HasPrefix predicate on the "song_id" field.
func SongIDHasPrefix(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldHasPrefix(FieldSongID, v))
}

// SongIDHasSuffix applies the HasSuffix predicate on the "song_id" field.
func SongIDHasSuffix(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldHasSuffix(FieldSongID, v))
}

// SongIDEqualFold applies the EqualFold predicate on the "song_id" field.
func SongIDEqualFold(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEqualFold(FieldSongID, v))
}

// SongIDContainsFold applies the ContainsFold predicate on the "song_id" field.
func SongIDContainsFold(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldContainsFold(FieldSongID, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int32) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int32) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int32) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int32) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int32) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int32) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int32) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int32) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldPosition, v))
}

// AddedByEQ applies the EQ predicate on the "added_by" field.
func AddedByEQ(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldAddedBy, v))
}

// AddedByNEQ applies the NEQ predicate on the "added_by" field.
func AddedByNEQ(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldAddedBy, v))
}

// AddedByIn applies the In predicate on the "added_by" field.
func AddedByIn(vs ...string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldAddedBy, vs...))
}

// AddedByNotIn applies the NotIn predicate on the "added_by" field.
func AddedByNotIn(vs ...string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldAddedBy, vs...))
}

// AddedByGT applies the GT predicate on the "added_by" field.
func AddedByGT(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldAddedBy, v))
}

// AddedByGTE applies the GTE predicate on the "added_by" field.
func AddedByGTE(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldAddedBy, v))
}

// AddedByLT applies the LT predicate on the "added_by" field.
func AddedByLT(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldAddedBy, v))
}

// AddedByLTE applies the LTE predicate on the "added_by" field.
func AddedByLTE(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldAddedBy, v))
}

// AddedByContains applies the Contains predicate on the "added_by" field.
func AddedByContains(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldContains(FieldAddedBy, v))
}

// AddedByHasPrefix applies the HasPrefix predicate on the "added_by" field.
func AddedByHasPrefix(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldHasPrefix(FieldAddedBy, v))
}

// AddedByHasSuffix applies the HasSuffix predicate on the "added_by" field.
func AddedByHasSuffix(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldHasSuffix(FieldAddedBy, v))
}

// AddedByEqualFold applies the EqualFold predicate on the "added_by" field.
func AddedByEqualFold(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEqualFold(FieldAddedBy, v))
}

// AddedByContainsFold applies the ContainsFold predicate on the "added_by" field.
func AddedByContainsFold(v string) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldContainsFold(FieldAddedBy, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlaylistSong) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlaylistSong) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlaylistSong) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.NotPredicates(p))
}
