// Code generated by ent, DO NOT EDIT.

package lyric

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/inkOrCloud/EchoVault/echovault-server/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContainsFold(FieldID, id))
}

// SongID applies equality check predicate on the "song_id" field. It's identical to SongIDEQ.
func SongID(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldSongID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldContent, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldType, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldLanguage, v))
}

// OffsetMs applies equality check predicate on the "offset_ms" field. It's identical to OffsetMsEQ.
func OffsetMs(v int32) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldOffsetMs, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldSource, v))
}

// IsDeleted applies equality check predicate on the "is_deleted" field. It's identical to IsDeletedEQ.
func IsDeleted(v bool) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldIsDeleted, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldUpdatedAt, v))
}

// SongIDEQ applies the EQ predicate on the "song_id" field.
func SongIDEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldSongID, v))
}

// SongIDNEQ applies the NEQ predicate on the "song_id" field.
func SongIDNEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldSongID, v))
}

// SongIDIn applies the In predicate on the "song_id" field.
func SongIDIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldSongID, vs...))
}

// SongIDNotIn applies the NotIn predicate on the "song_id" field.
func SongIDNotIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldSongID, vs...))
}

// SongIDGT applies the GT predicate on the "song_id" field.
func SongIDGT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldSongID, v))
}

// SongIDGTE applies the GTE predicate on the "song_id" field.
func SongIDGTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldSongID, v))
}

// SongIDLT applies the LT predicate on the "song_id" field.
func SongIDLT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldSongID, v))
}

// SongIDLTE applies the LTE predicate on the "song_id" field.
func SongIDLTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldSongID, v))
}

// SongIDContains applies the Contains predicate on the "song_id" field.
func SongIDContains(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContains(FieldSongID, v))
}

// SongIDHasPrefix applies the HasPrefix predicate on the "song_id" field.
func SongIDHasPrefix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasPrefix(FieldSongID, v))
}

// SongIDHasSuffix applies the HasSuffix predicate on the "song_id" field.
func SongIDHasSuffix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasSuffix(FieldSongID, v))
}

// SongIDEqualFold applies the EqualFold predicate on the "song_id" field.
func SongIDEqualFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEqualFold(FieldSongID, v))
}

// SongIDContainsFold applies the ContainsFold predicate on the "song_id" field.
func SongIDContainsFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContainsFold(FieldSongID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContainsFold(FieldContent, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContainsFold(FieldType, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContainsFold(FieldLanguage, v))
}

// OffsetMsEQ applies the EQ predicate on the "offset_ms" field.
func OffsetMsEQ(v int32) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldOffsetMs, v))
}

// OffsetMsNEQ applies the NEQ predicate on the "offset_ms" field.
func OffsetMsNEQ(v int32) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldOffsetMs, v))
}

// OffsetMsIn applies the In predicate on the "offset_ms" field.
func OffsetMsIn(vs ...int32) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldOffsetMs, vs...))
}

// OffsetMsNotIn applies the NotIn predicate on the "offset_ms" field.
func OffsetMsNotIn(vs ...int32) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldOffsetMs, vs...))
}

// OffsetMsGT applies the GT predicate on the "offset_ms" field.
func OffsetMsGT(v int32) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldOffsetMs, v))
}

// OffsetMsGTE applies the GTE predicate on the "offset_ms" field.
func OffsetMsGTE(v int32) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldOffsetMs, v))
}

// OffsetMsLT applies the LT predicate on the "offset_ms" field.
func OffsetMsLT(v int32) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldOffsetMs, v))
}

// OffsetMsLTE applies the LTE predicate on the "offset_ms" field.
func OffsetMsLTE(v int32) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldOffsetMs, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Lyric {
	return predicate.Lyric(sql.FieldContainsFold(FieldSource, v))
}

// IsDeletedEQ applies the EQ predicate on the "is_deleted" field.
func IsDeletedEQ(v bool) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldIsDeleted, v))
}

// IsDeletedNEQ applies the NEQ predicate on the "is_deleted" field.
func IsDeletedNEQ(v bool) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldIsDeleted, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Lyric {
	return predicate.Lyric(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Lyric) predicate.Lyric {
	return predicate.Lyric(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Lyric) predicate.Lyric {
	return predicate.Lyric(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Lyric) predicate.Lyric {
	return predicate.Lyric(sql.NotPredicates(p))
}
